feat：修复source变化后视图不更新，调整部分文案
baidu/amis pull request #11106
Opened 2024-10-24 12:49 UTC by F-jianchao

### What

### Why

### How

2024-11-01 02:17 UTC, 2betop requested changes
component 应该不用关注 source 问题，请调整

2024-11-04 06:06 UTC, F-jianchao commented
> component 应该不用关注 source 问题，请调整

已调整

2024-11-04 11:20 UTC, 2betop approved these changes

2024-11-04 11:44 UTC, CheshireJCat approved these changes

2024-11-04 11:44 UTC, merged