feat:组件广播事件机制
baidu/amis pull request #3326
Opened 2021-12-31 08:54 UTC by hsm-lv

2022-01-04 02:40 UTC, 2betop requested changes

2022-01-04 02:40 UTC, 2betop commented on src/SchemaRenderer.tsx
> +        {...this.props}
这个顺序有问题，应该把 dispatchEvent 放到最好，否则深层次的渲染器中，拿到的 dispatchEvent 不正确

2022-01-04 02:40 UTC, 2betop commented on src/actions/Action.ts
> +    actionConfig.args &&
这个逻辑应该在 runAction里面吧，并且是 execOn 后面

2022-01-04 02:40 UTC, 2betop commented on src/factory.tsx
> +        console.warn(`Unknown renderer event: ${eventName}`);
没有找到可能是没配置，没配置为何会是 warn 呢。通常默认都不会配置吧。

2022-01-04 02:40 UTC, 2betop commented on src/factory.tsx
> +        rendererEvent.setData(
这个应该在 broadcastAction 里面吧。

2022-01-04 02:40 UTC, 2betop commented on src/actions/LoopAction.ts
> +          createObject(protoData, {
应该直接用 event.data, 否则数据会丢失一层。

```
createObject(event.data, data)
```

2022-01-04 02:40 UTC, 2betop commented on src/actions/LoopAction.ts
> +            event.setData(protoData);
还原代码有问题，之前缓存的数据会导致原型链断开，上层数据都没了

2022-01-04 02:40 UTC, 2betop commented on src/actions/Action.ts
> +    actionConfig.preventDefault && event.preventDefault();
这两个应该在 runAction 里面？

2022-01-04 02:40 UTC, 2betop commented on src/actions/ParallelAction.ts
> +      const childActions = action.children.map((child: LogicAction) => {
这两个变量有什么用？下面为何不支持用 event 对象判断？

2022-01-04 02:40 UTC, 2betop commented on src/actions/SwitchAction.ts
> +        branch.stopPropagation && event.stopPropagation();
这两处重复了， runActionTree 里面已经执行过了

2022-01-04 02:40 UTC, 2betop commented on src/factory.tsx
> +        for (let key in listeners) {
不需要遍历 listeners 直接 this.rendererEventListeners 中 renderer 相同的项过滤掉就行了。没必要做多次 findIndex，这样不管绑定多少次事件，只需要一次遍历。

2022-01-04 02:40 UTC, 2betop commented on src/factory.tsx
> +        eventData: data
应该是 data ？

2022-01-04 03:16 UTC, hsm-lv commented on src/actions/Action.ts
> +    actionConfig.args &&
嗯嗯，是的😄

2022-01-04 03:24 UTC, hsm-lv commented on src/factory.tsx
> +        rendererEvent.setData(
okk

2022-01-04 03:24 UTC, hsm-lv commented on src/factory.tsx
> +        console.warn(`Unknown renderer event: ${eventName}`);
改用log

2022-01-04 06:02 UTC, hsm-lv commented on src/factory.tsx
> +        rendererEvent.setData(
诶？这个不能放broadcastAction里面，因为这里需要那监听的renderer而不是触发端的

2022-01-04 06:17 UTC, hsm-lv commented on src/actions/LoopAction.ts
> +          createObject(protoData, {
每层只设置当前层的数据也是合理的吧？还需要每层的都带上吗？

2022-01-04 06:33 UTC, hsm-lv commented on src/actions/SwitchAction.ts
> +        branch.stopPropagation && event.stopPropagation();
这个其实是忘记await了-_-

2022-01-04 06:43 UTC, hsm-lv commented on src/factory.tsx
> +        for (let key in listeners) {
是哦，按照key没啥意义了

2022-01-04 06:51 UTC, hsm-lv commented on src/actions/ParallelAction.ts
> +      const childActions = action.children.map((child: LogicAction) => {
懂了懂了

2022-01-04 14:30 UTC, 2betop requested changes

2022-01-04 14:30 UTC, 2betop commented on src/actions/CmptAction.ts
> +      ...event.data.__proto__,
直接就 action.args 就可以了吧，runAction 已经统一了 args 的值

2022-01-04 14:30 UTC, 2betop commented on src/actions/LoopAction.ts
> +      const protoData = {...event.data.__proto__};
应该是这样
const protoData = event.data;

2022-01-04 14:30 UTC, 2betop commented on src/factory.tsx
> +        const idx = findIndex(
不是这个意思，应该是这样

this.rendererEventListeners = this.rendererEventListeners.filter(item => item.renderer === renderer);

因为有可能有多个actions，你前面的写法会只删除一个。

2022-01-05 01:58 UTC, hsm-lv commented on src/actions/CmptAction.ts
> +      ...event.data.__proto__,
嗯呢，可以都在runAction里面处理最后的数据

2022-01-05 08:17 UTC, merged