Feat/input range
baidu/amis pull request #3405
Opened 2022-01-13 13:16 UTC by kano233333

feat: inputRange组件

2022-01-18 08:15 UTC, hsm-lv requested changes

2022-01-18 08:15 UTC, hsm-lv commented on src/components/Range.tsx
> +       auto: 'pos-top',
auto那个可以看下Overlay，看下其他组件的处理

2022-01-18 08:15 UTC, hsm-lv commented on src/components/Range.tsx
> +       valueToOffsetLeft: (value: number) => this.valueToOffsetLeft(value)
既然必须属性，为啥不直接在handleItem里面直接绑定？

2022-01-18 08:15 UTC, hsm-lv commented on src/components/Range.tsx
> +         <HandleItem {...props} onChange={this.onChange.bind(this)} value={+value} />
为啥这还包个div

2022-01-18 08:15 UTC, hsm-lv commented on src/components/Range.tsx
> +         <Track {...props}>
组件封装较多，可以合并一下

2022-01-18 08:15 UTC, hsm-lv commented on src/renderers/Form/InputRange.tsx
> +      ...RangeControl.defaultProps,
这里为啥还要去手动覆盖defaultProps

2022-02-14 09:02 UTC, hsm-lv requested changes

2022-02-15 08:37 UTC, hsm-lv approved these changes

2022-02-15 08:41 UTC, 2betop commented
代码冲突了，需要修改

2022-02-15 09:03 UTC, hsm-lv approved these changes

2022-02-16 15:55 UTC, 2betop requested changes
总体没啥大问题，还有些小修改请参考行评论完成。

2022-02-16 15:55 UTC, 2betop commented on src/components/Range.tsx
>  }
看一下 themeable，通常组件都会被 themable 包一下，输出带前缀的 className 都是通过 props.classnames 去生成的。请改成这种形式

2022-02-17 03:31 UTC, kano233333 commented on src/components/Range.tsx
>  }
这个是在最后包裹的，辛苦再看看～
export default themeable(
  uncontrollable(Range, {
    value: 'onChange'
  })
);

2022-02-18 04:44 UTC, merged