feat: input-text支持事件动作
baidu/amis pull request #3485
Opened 2022-01-24 10:34 UTC by lurunze1226

2022-01-25 02:45 UTC, hsm-lv requested changes

2022-01-25 02:45 UTC, hsm-lv commented on src/renderers/Form/InputText.tsx
> +  return dispatchEvent(e, createObject(data, {...ctx}));
createObject(data, ctx)

2022-01-25 02:45 UTC, hsm-lv commented on src/renderers/Form/InputText.tsx
其他组件调用输入框的动作处理还没有加？

2022-01-25 12:24 UTC, lurunze1226 commented on src/actions/CmptAction.ts
> +    if (!component) {
如果没有指定组件id，component拿不到，这里报错信息不明显

2022-01-26 06:09 UTC, hsm-lv requested changes

2022-01-26 06:09 UTC, hsm-lv commented on src/renderers/Form/InputText.tsx
> +    } else if (actionType === 'change') {
change动作暂不这么加，先去掉吧

2022-01-26 07:06 UTC, hsm-lv approved these changes

2022-01-26 07:10 UTC, hsm-lv approved these changes

2022-01-26 07:32 UTC, merged