feat: Textarea/Editor/DiffEditor动作事件扩充
baidu/amis pull request #3589
Opened 2022-02-15 09:35 UTC by lurunze1226

2022-02-15 10:53 UTC, hsm-lv requested changes

2022-02-15 10:53 UTC, hsm-lv commented on src/actions/Decorators.ts
> +export type InputRendererEvent =
感觉在这里定义输入类组件的事件动作跟在组件里面没太大差异

2022-02-15 10:53 UTC, hsm-lv commented on examples/components/EventAction/InputEvent.jsx
> +      body: [
demo里面可以补下事件派发的动作，例如：
onEvent: {
                blur: {
                  actions: [
                    {
                      actionType: 'toast',
                      msgType: 'info',
                      msg: '派发blur事件'
                    }
                  ]
                },
                focus: {
                  actions: [
                    {
                      actionType: 'toast',
                      msgType: 'info',
                      msg: '派发focus事件'
                    }
                  ]
                },
                change: {
                  actions: [
                    {
                      actionType: 'toast',
                      msgType: 'info',
                      msg: '派发change事件'
                    }
                  ]
                }
              }

2022-02-16 02:23 UTC, lurunze1226 commented on src/actions/Decorators.ts
> +export type InputRendererEvent =
可以，本来是想输入类型的渲染器事件比较通用。还是放在组件里比较好，这样方便查看每个组件支持的事件

2022-02-16 03:01 UTC, hsm-lv approved these changes

2022-02-16 03:01 UTC, hsm-lv commented
看下单测

2022-02-16 03:22 UTC, merged