form 事件&动作扩充
baidu/amis pull request #3597
Opened 2022-02-16 09:10 UTC by pianruijie

2022-02-16 11:21 UTC, hsm-lv requested changes

2022-02-16 11:21 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +    if (actionType === 'submit' || actionType === 'confirm') {
这里可以不动吧，动作是不是都包含进来了

2022-02-18 07:11 UTC, pianruijie commented
修复问题

2022-03-23 13:44 UTC, hsm-lv requested changes

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +      dispatchEvent('validateFail', createObject(data));
如果只有data就不用createObject包裹了

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +        dispatchEvent('validateSucc', createObject(data));
如果只有data就不用createObject包裹了

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +          dispatchEvent('validateError', createObject(this.props.data));
1

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +          dispatchEvent('validateSucc', createObject(this.props.data));
1

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/index.tsx
> +  doAction(action: Action, data: object, throwErrors: boolean) {
这里应该不需要改啥

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/wrapControl.tsx
> +                formItemDispatchEvent('formItemValidateError', createObject(data));
1

2022-03-23 13:44 UTC, hsm-lv commented on src/renderers/Form/wrapControl.tsx
> +                formItemDispatchEvent('formItemValidateSucc', createObject(data));
1

2022-03-24 03:08 UTC, pianruijie commented on src/renderers/Form/index.tsx
> +        dispatchEvent('validateSucc', createObject(data));
目前拿不到，需要对store改造一下，能拿到报错提示，这个有意义么

2022-03-24 04:24 UTC, hsm-lv approved these changes

2022-03-24 05:25 UTC, merged