feat: page下拉刷新配置
baidu/amis pull request #3788
Opened 2022-03-16 12:11 UTC by hy993658052

2022-03-16 13:18 UTC, 2betop commented
标题改一下？应该是事件动作相关功能

2022-03-18 12:22 UTC, hsm-lv requested changes

2022-03-18 12:22 UTC, hsm-lv commented on src/renderers/Page.tsx
> +    return this.handleAction(undefined, action, data);
这里本意是专有动作，如果page没有专有动作可以先不加

2022-03-22 09:52 UTC, hsm-lv approved these changes

2022-03-22 09:52 UTC, merged