表单提交时间支持禁用默认提示
baidu/amis pull request #4255
Opened 2022-05-07 11:42 UTC by pianruijie

2022-05-09 02:02 UTC, hsm-lv requested changes

2022-05-09 02:02 UTC, hsm-lv commented on src/store/form.ts
> +        if (!ret?.dispatcher?.prevented) {
if (ret?.dispatcher?.prevented) {return}是不是更清晰

2022-05-09 02:02 UTC, hsm-lv commented on src/store/form.ts
> +          const dispatcher: any = validateErrCb && validateErrCb();
await

2022-05-09 09:16 UTC, pianruijie commented on src/store/form.ts
> +        let ret = options && options.onFailed && options.onFailed(e.response || {});
因为error的toast在这里，需要拿到dispatcher

2022-05-09 09:16 UTC, pianruijie commented on src/store/form.ts
> +          let ret = options && options.onSuccess && options.onSuccess(json);
下面用了yield

2022-05-09 09:17 UTC, pianruijie commented on src/store/form.ts
> +        let ret = options && options.onFailed && options.onFailed(e.response || {});
下面用了yield

2022-05-09 09:18 UTC, pianruijie commented on src/store/form.ts
> +        if (!ret?.dispatcher?.prevented) {
不能阻断执行逻辑，只能控制notify逻辑

2022-05-09 09:18 UTC, pianruijie commented on src/store/form.ts
> +          const dispatcher: any = validateErrCb && validateErrCb();
用了yield

2022-05-09 13:51 UTC, hsm-lv approved these changes

2022-05-09 13:52 UTC, merged

2022-09-06 07:56 UTC, rumunanfeng commented on src/store/form.ts
> +          const dispatcher: any = validateErrCb && validateErrCb();
还是没理解要如何禁用默认提示，望大佬不吝赐教 @hsm-lv @pianruijie

2022-09-06 08:02 UTC, hsm-lv commented on src/store/form.ts
> +          const dispatcher: any = validateErrCb && validateErrCb();
> 还是没理解要如何禁用默认提示，望大佬不吝赐教 @hsm-lv @pianruijie

试下事件干预，https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E9%98%BB%E6%AD%A2%E4%BA%8B%E4%BB%B6%E9%BB%98%E8%AE%A4%E8%A1%8C%E4%B8%BA

2022-09-06 08:07 UTC, rumunanfeng commented on src/store/form.ts
> +          const dispatcher: any = validateErrCb && validateErrCb();
> > 还是没理解要如何禁用默认提示，望大佬不吝赐教 @hsm-lv @pianruijie
> 
> 试下事件干预，https://baidu.github.io/amis/zh-CN/docs/concepts/event-action#%E9%98%BB%E6%AD%A2%E4%BA%8B%E4%BB%B6%E9%BB%98%E8%AE%A4%E8%A1%8C%E4%B8%BA

感谢大佬，action里面配置："preventDefault": true 就可以了