组件默认值支持公式表达式
baidu/amis pull request #4315
Opened 2022-05-12 03:54 UTC by wibetter

可执行 ${} 格式类表达式，且支持 filter 过滤器。

2022-05-12 06:17 UTC, 2betop requested changes

2022-05-12 06:17 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
表单是会动态创建的，因为显隐联动出现了一个待公式的表单项，这个逻辑会让新值变成了表单项的初始值，即 prinstine 值。 这是不符合预期的，应该只是改值本身。 下面的逻辑实际是上初始化设置进去，下面的逻辑本身就会把公式计算出来的初始值设置进去，所以这不需要再处理了。

2022-05-12 06:17 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +                value: isPureValue(props.$schema.value) ? props.$schema.value : formulaExec(props.$schema.value, props.data, false), // props.$schema.value,
model.config 貌似都没接收 value ，所以不需要下发了

2022-05-12 06:17 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +                const curResult = formulaExec(props.value, props.data, false);
计算公式不要 props.value 而是 props.defaultValue

另外需要考虑外部控制 value 的场景，外部控制 value，是不需要运行公司的。外部下发的 props.value 是什么就给model 的 tmpValue 设置什么。

目前这样外部无法控制 value 了，就是 props 下发个 value 更新了，表单项 ui 空间的值不变。

2022-05-12 06:17 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
公式变化，算出来的新值直接设置到 tmpValue 上真的有用吗？外部貌似接收不到啊除非做一次修改才会提交上去

2022-05-12 07:02 UTC, wibetter commented on src/utils/helper.ts
> +    return JSON.stringify(value);
formulaExec是用来执行表达式的，value本就不该设置object对象数据吧，

2022-05-12 07:04 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
用于识别表达式是"xxx"、'xxx'，这种纯字符串的形式有必要走运算器吗？

2022-05-12 07:04 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
同上

2022-05-12 07:05 UTC, wibetter commented on src/utils/helper.ts
> +  const formulaKey = catchFormulaExecSign(curValue);
方便后续有需要的时候，基于扩展性考虑，目前暂未用到。

2022-05-12 07:06 UTC, wibetter commented on src/utils/helper.ts
> +    // 普通字符串类型（非表达式），先试一下从上下文中获取数据
非${}格式目前不支持，如果需要执行aaa.bb 或者 aaa[bb]，可改用${aaa.bb} 或者 ${aaa[bb]}。

2022-05-12 07:09 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            model.changeTmpValue(curTmpValue);
这里是初始化，constructor，外部控制在componentDidUpdate处理

2022-05-12 07:10 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
这里主要的作用是将计算后的值同步到上下文中，

2022-05-12 07:11 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
拿掉就会出问题，

2022-05-12 07:13 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                const curResult = formulaExec(props.value, props.data, false);
这里确实可以优化下，改成model.changeTmpValue(props.value)。

2022-05-12 07:14 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
不设置给tmpValue哪设置给谁啊？

2022-05-12 08:11 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
\'hello，world\'  和 \"hello，world\"，会直接原样输出，没在这里处理。

2022-05-12 08:12 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
![image](https://user-images.githubusercontent.com/11958920/168023888-f34e5362-a311-4a9a-a013-7e3a4e987534.png)

2022-05-12 08:15 UTC, 2betop commented on src/utils/helper.ts
> +    return JSON.stringify(value);
这种 value 就不应该进来，只有字符串才计算公式

2022-05-12 08:17 UTC, 2betop commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
我是指 'abc \' efg \t bla bla \n' 等等

2022-05-12 08:20 UTC, 2betop commented on src/utils/helper.ts
> +  const formulaKey = catchFormulaExecSign(curValue);
这种语法不打算扩充，所以不需要实现

2022-05-12 08:20 UTC, 2betop commented on src/utils/helper.ts
> +    // 普通字符串类型（非表达式），先试一下从上下文中获取数据
要不就不要扩充，要扩充就完全对齐

2022-05-12 08:22 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +            model.changeTmpValue(curTmpValue);
你没明白我说的外部控制是什么意思，就是那种把渲染器当组件使用的场景，给这个组件直接下发 value，这个 value 由使用者来控制，更新后会下发新的 value 。

2022-05-12 08:24 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
onChange 的第四个参数是 true，以为设置值后，还会把  prinstine 值也修改，这个场景是不应该修改 prinstine 的

2022-05-12 08:25 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
我的意思是设置 tmpValue 不够，要 onChange 出去

2022-05-12 09:21 UTC, wibetter commented on src/utils/helper.ts
> +    // 普通字符串类型（非表达式），先试一下从上下文中获取数据
将formulaExec(props.$schema.value, props.data, false)改成formulaExec(props.$schema.value, props.data, true)即可

2022-05-12 09:27 UTC, wibetter commented on src/utils/helper.ts
> +    return JSON.stringify(value);
这里的目的难道不是过滤掉这类object 和 array类型，避免进行公式运算吗？是指要在wrapControl中执行formulaExec前加一个条件？

2022-05-12 09:29 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
![image](https://user-images.githubusercontent.com/11958920/168039231-6b0e9708-3b7c-4f17-8f26-1dfc51142201.png)

2022-05-12 09:31 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
![image](https://user-images.githubusercontent.com/11958920/168039528-e360a75b-725d-47b1-875d-fe275394190c.png)

2022-05-12 09:37 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
prinstine是什么属性，是做什么的？目前看amis没有一行关于prinstine的注释和说明，

2022-05-12 09:56 UTC, 2betop commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
图 1 不符合预期

2022-05-12 09:59 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
此前的逻辑在哪？didUpdate 里面没看到有相关逻辑啊

2022-05-12 10:48 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
那这块确实还需要优化下，目前确实没有考虑到这种情况。

2022-05-12 10:50 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
每次表达式编辑后，会走handleChange，

2022-05-12 10:51 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
哦，你说的是非编辑器端时，关联变动的变动场景，这么说确实需要补上onChange。

2022-05-12 11:08 UTC, wibetter commented on src/utils/helper.ts
> +    return value.substring(1, value.length - 1);
@2betop  https://github.com/baidu/amis/pull/4315/commits/44f176b4e773a9ca547e2ba11c18b2bd266b1806

2022-05-12 11:12 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            model.changeTmpValue(curTmpValue);
已改成优先使用propValue了：
<img width="876" alt="image" src="https://user-images.githubusercontent.com/11958920/168060489-182e45da-92dc-4890-8291-42a20fa40131.png">

2022-05-12 11:17 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                  model.changeTmpValue(curResult);
@2betop 之前的代码中，name值关联的变量变动后也是没有执行onChange：
<img width="757" alt="image" src="https://user-images.githubusercontent.com/11958920/168062648-723c6268-4f73-42c0-8d62-7dd93af98b76.png">
，这里是不是同样存在你说的问题，要不要顺带补上

2022-05-12 11:31 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +            if (onChange && value !== undefined && curTmpValue !== undefined) {
这里是不是也得改成false？
<img width="771" alt="image" src="https://user-images.githubusercontent.com/11958920/168065230-ec2d5179-1c4e-4067-878e-dd430db4bd0c.png">

2022-05-12 11:41 UTC, wibetter commented on src/renderers/Form/wrapControl.tsx
> +                value: isPureValue(props.$schema.value) ? props.$schema.value : formulaExec(props.$schema.value, props.data, false), // props.$schema.value,
这里确实有点多余，已改回 props.$schema.value。

2022-05-13 03:59 UTC, nwind commented on __tests__/renderers/__snapshots__/Page.test.tsx.snap
> -                        value="2"
这里应该就是 2 的，不应该更新 snapshot

2022-05-13 05:16 UTC, wibetter commented
@2betop 最后反馈的问题，我记在这里了：
（备注：尤其是3，表示不接受保留）
1. propValue 模式，有多余的公式运算，同时会伴随有 onChange 动作。虽然这个模式不大可能会下发 defaultValue，但是存在不符合预期的修改值风险
2. 启动不启动 公式是根据用不用 ${} 语法来启动的，这个规则早在群里就讨论了，不要判断是不是纯变量默认，因为有点多余，凡是没用 ${} 语法就都认为是普通值就行，尤其是这种判断 ${[xxxemail@xxx.com](mailto:xxxemail@xxx.com)} 既不是合法的数值，也不是合法的表达式语法，完全不明白要判断的原因是什么。
3. 把 var:xxx, js:xxx, =:xxx 语法干掉，不打算给用户扩充，就不要保留这类代码即便是调用时用参数关了。
4. 补充测试用例覆盖以下场景：
   1. `普通文字带一个$，不应该启用公式，带转义的 \${abc} 也不启用` 渲染器后值就是当前原始值
   2. '文本 ${abc}' 这个默认值需要启动公式，且验证新值初始是否在上下文中，关联 abc 修改后，新值是否在上下文中。
   3. 自定义组件中直接 this.props.render('inner', {type: 'input-text', name: 'a', label: 'xxx'}, {value: controlledValue}) 用法初始是否展示正确，修改 controlledValue 后是否展示正确。

2022-05-13 05:41 UTC, wibetter commented
@2betop 接上条，
1. 不存在你说的问题1，确认下相关代码是否没看全；
2. 组件默认值，目前就是根据是否是${}启动运算器，在warpControl中至于加isPureValue判断并不多余，方便需要的时候（启动非${}运算模式，当然一般情况用不上）可以过滤日期、邮件等特殊格式字符串；
3. 目前 var:xxx, js:xxx, =:xxx 语法并没有用在组件默认值支持表达式中，至于他的作用，已经在源码中注释说明了：用于线上开启 OpenFormulaExecEvalMode，方便线上环境可以指定运算器类型进行debug；
4. 代码确认没有较大缺陷时，会补上。

2022-05-13 12:47 UTC, 2betop commented
1. 如果是 propValue 控制模式， model.changeTmpValue(propValue); 是有用的，其他都是多余的。而且因为有公式运算，成本较大，应该跳过 

https://github.com/baidu/amis/blob/be49426f7e9c9b2392d624f15083a5ce740db709/src/renderers/Form/wrapControl.tsx#L202-L210

2. 不认为需要切到 非${}运算模式，早就内部讨论了非${}运算模式就认为是普通文本。
3. 都没说要给用户支持这个语法，哪来的debug需求？

2022-05-13 13:26 UTC, wibetter commented
@2betop 看截图，问题1 在propValue使用场景下，确实没必要执行:
`
const curValue = isPureValue(value) ? value : formulaExec(value, data, false); // 对组件默认值进行运算 
`
这里我再调整下执行顺序，优化下判断条件。

至于问题2、问题3，我也不纠结这个小功能点了，就按你说的先注释掉，后续有需要我再补上。

2022-05-13 13:58 UTC, wibetter commented
@2betop 这里说的debug是指，浏览器控制台执行window.updateFormulaExecEvalModeDefaultStatus(true)后，组件默认值value中，就可以指定任何一个运算器测试一下当前的表达式是否符合预期。比如：使用 js:data.test + 1 看一下走 js运算器 结果是什么样的？使用 var:test 能不能直接拿到父作用域中test的数值？你是对debug有误解还是咱两的理解不一样呢？

2022-05-13 14:58 UTC, 2betop commented
浏览器控制直接 $r.props.data 就能查看上下文数据，表达式稍微改一下，就能用 控制台跑出结果，现有的debug方式已经够用了，而且比 updateFormulaExecEvalModeDefaultStatus 便捷

2022-05-13 16:17 UTC, wibetter commented
表示“浏览器控制直接 $r.props.data 就能查看上下文数据，表达式稍微改一下，就能用 控制台跑出结果”只是看上下文的数据，跟通过在schema或者编辑面板中改表达式看结果，感觉没啥区别吧。

2022-05-16 06:14 UTC, wibetter commented
@2betop 已修复测试用例，并补充部分组件默认值支持公式运算测试用例。

2022-05-17 01:27 UTC, nwind commented on __tests__/renderers/Page.test.tsx
> -                  value: '3'
不能改

2022-05-17 11:26 UTC, 2betop commented on src/utils/formula.ts
> +  return /(\${).+(\})/.test(expression);
关看是否有 ${ } 包裹也不太准确，因为有可能前面的 dollor 转义了。如果不考虑其他语法比如 raw: 和 = 之类的，这里快速比较准确的方式应该是，先看有没有 ${ 没有直接 return false, 有的话，用  amis-formula 拿到 ast，看 第一个成员的数量大于 1 应该就是由表达式的。

2022-05-17 12:02 UTC, 2betop commented on src/renderers/Form/wrapControl.tsx
> +              const valueByName = getVariable(props.data, model.name);
这里的改动风险很大，不知道为何要修改？能说一下什么场景不满足吗？

2022-05-19 02:51 UTC, merged