feat: inputCity支持多选
baidu/amis pull request #4338
Opened 2022-05-13 10:05 UTC by meerkat-morecats

- 更新input-city单测
- 修正CityDB数据
- 去掉 allowStreet props

2022-05-20 03:04 UTC, meerkat-morecats commented on src/renderers/Form/InputCity.tsx
> +            'input-city',
不太确定这样给了个 path 之后会不会对其他逻辑有影响

2022-05-23 02:54 UTC, lurunze1226 commented on __tests__/renderers/Form/city.test.tsx
> +  fireEvent.click(getByText('长安区'));
补充一下多选属性的UT吧

2022-05-23 02:54 UTC, lurunze1226 commented on docs/zh-CN/components/form/input-city.md
> +}
说一下几个问题
- 这个多选有点问题，无法选择到叶节点
- 全选会选择所有的省份，理论上深度应该和allowXXX相匹配
- 街道详细地址的输入丢失了
- searchable属性失效了，开启之后没有搜索框了

2022-05-23 02:54 UTC, lurunze1226 commented on src/renderers/Form/CityDB.ts
> +  120000: '天津市',
这个顺序最好不要换，是按照省级区划分割开的

2022-05-23 02:54 UTC, lurunze1226 commented on src/renderers/Form/InputCity.tsx
> -  allowStreet?: boolean;
旧属性不要干掉，可能有用户在使用，而且这个属性是有用的，街道这块交互需要再设计一下，输入框单独放出来更好一些

2022-05-23 02:54 UTC, lurunze1226 commented on src/renderers/Form/InputCity.tsx
> +      this.setState({
通过配置更新`allowCity ` 或者 `allowDistrict ` 没有实时生效

2022-05-23 02:54 UTC, lurunze1226 commented on src/renderers/Form/InputCity.tsx
> +            'input-city',
这个没影响

2022-05-26 09:32 UTC, meerkat-morecats commented on src/renderers/Form/CityDB.ts
> +  120000: '天津市',
这个顺序没影响的，主要这次的数据源是这个顺序，我觉得只要他有一个排列规则就好吧，新的数据看着是按层级排序的

2022-05-30 07:10 UTC, meerkat-morecats commented on src/renderers/Form/InputCity.tsx
> +      this.setState({
这应该是一个FormItem的bug，或者是CheckboxControlRenderer的bug，需要调用一次onChange才会将属性同步

2022-05-30 07:13 UTC, meerkat-morecats commented on docs/zh-CN/components/form/input-city.md
> +}
> 说一下几个问题
> 
> * 这个多选有点问题，无法选择到叶节点
> * 全选会选择所有的省份，理论上深度应该和allowXXX相匹配
> * 街道详细地址的输入丢失了
> * searchable属性失效了，开启之后没有搜索框了

1. 意思是选择了北京市，实际应该出现所有`区`所代表的tag？
2. search是在select内部可以搜索，本来就没有搜索框

2022-07-21 13:00 UTC, lurunze1226 requested changes

2022-07-21 13:00 UTC, lurunze1226 commented on packages/amis-ui/scss/components/_result-box.scss
> +  justify-content: space-between;
这个确认一下有没有影响

2022-07-21 13:00 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/InputCity.tsx
> +    const db = this.state.db!;
下面有判断的话这里可以不用断言了

2022-07-21 13:00 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/NestedSelect.tsx
> +                        ? this.handleCheck(option)
这里第二个参数丢失了

2022-07-21 13:00 UTC, lurunze1226 commented on packages/amis-ui/scss/components/_result-box.scss
> +    padding-right: calc(var(--Form-input-paddingX) - #{px2rem(3px)});
![image](https://user-images.githubusercontent.com/36724300/180218308-338c4d2b-ab1d-47b6-8178-4dc6dfcb1c27.png)
不太确定是哪个样式影响了，检查一下

2023-05-05 03:17 UTC, closed without merging