fix: 修复table无法勾选的
baidu/amis pull request #4829
Opened 2022-07-08 07:52 UTC by meerkat-morecats

fix: 修复table无法勾选的

2022-07-08 08:10 UTC, lurunze1226 commented on packages/amis/src/renderers/Table/index.tsx
> +    console.log(store.filteredColumns);
log

2022-07-08 08:10 UTC, lurunze1226 commented on packages/amis/src/renderers/Table/index.tsx
> +    console.log(store.filteredColumns);
单测更新一下

2022-07-09 05:55 UTC, meerkat-morecats commented on packages/amis/src/renderers/Table/index.tsx
> +    console.log(store.filteredColumns);
ok

2022-07-12 02:36 UTC, lurunze1226 requested changes

2022-07-12 02:36 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/Table.test.tsx
> +test('Renderer:table selectable', async () => {
这个建议用describe分组处理一下，radio 和 check 每个对应一个test，还有item禁用状态的case

2022-07-12 03:42 UTC, merged