补充crud单测
baidu/amis pull request #4838
Opened 2022-07-11 06:58 UTC by meerkat-morecats

test: crud

2022-07-12 02:13 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  expect(mockFetcher.mock.calls.length).toEqual(2);
toHaveBeenCalledTimes 更语义化

2022-07-12 02:13 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  expect(mockFetcher2.mock.calls.length).toEqual(1);
这个怎么感觉像是bug了，如果条件是true的话，应该就不执行了

2022-07-12 02:13 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +test('Renderer:crud filter stopAutoRefreshWhen', async () => {
这里为啥有个stopAutoRefreshWhen

2022-07-12 02:30 UTC, meerkat-morecats commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  expect(mockFetcher2.mock.calls.length).toEqual(1);
> 这个怎么感觉像是bug了，如果条件是true的话，应该就不执行了

初始化的时候会执行一次

2022-07-14 03:27 UTC, lurunze1226 requested changes

2022-07-14 03:27 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  await waitFor(() => getByText('Internet Explorer 4.0'));
和mock数据耦合有点重，用mutationObserverOptions监听table dom结构变化似乎可以

2022-07-14 03:27 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  const {container, getByText, debug} = render(
没有用到的参数就删掉吧

2022-07-14 03:27 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/Table.test.tsx
> +describe('Renderer:table selectable&itemCheckableOn', () => {
`selectable & itemCheckableOn` 来个空格

2022-07-22 09:10 UTC, lurunze1226 requested changes

2022-07-22 09:10 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/CRUD.test.tsx
> +  expect(container).toMatchSnapshot();
这里少了bulkActions的交互

2022-07-25 02:47 UTC, merged