feat: 新增 icon-select 组件，用于速搭 svg icon 的使用
baidu/amis pull request #4869
Opened 2022-07-13 11:22 UTC by tooeast

新 icon 选择器，用于使用速搭 icon 管理的 svg 图标。
使用与现有 iconPicker 类似，但资源内容不同

2022-07-14 04:55 UTC, nwind commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +        <p className={cx(`${ns}IconSelectControl-icon-list-empty`)}>无符合条件图标</p>
翻译

2022-07-22 02:59 UTC, lurunze1226 requested changes

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelectStore.tsx
> +        name: '全部',
文案国际化

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelectStore.tsx
> +    });
这里map + flatten 可以实现吧，另外看下这个list是否需要去重

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelectStore.tsx
> +    name: '默认分类',
文案国际化

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelectStore.tsx
> +export interface SvgIconTypes {
这个类型定义是icon的分类吗，改成`SvgIconGroup`更语义化一点
`interface SvgIconGroup {name: string; groupId: string; children: SvgIcon[]}`

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +          >图标选择</Modal.Header>
文案i18n

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +            <Button type="button" className="m-l" onClick={() => this.toggleModel(false)}>取消</Button>
文案i18n

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +            <Button type="button" level="primary" onClick={this.handleConfirm}>确定</Button>
文案i18n

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +  getIconsByType() {
这个没必要bind

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +  activeTypeIndex: string | number;
这个类型应该保证是number，否则你下面取索引很麻烦

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +  type: 'icon-select';
IconSelectProps里primitive的props这里应该体现

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +          !value && !value && placeholder && (
重复判断了

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +  renderIconList(icons: any[]) {
icons的类型应该是已知的吧

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +
多了个空行，用prittier格式化处理一下

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/IconSelect.tsx
> +          IconSelectStore.refreshIconList && render('refresh',
'refresh-btn' , 功能名称 + 实体类型

2022-07-22 02:59 UTC, lurunze1226 commented on packages/amis/src/renderers/Icon.tsx
> +    if (icon && typeof icon === 'string' && icon.startsWith('svg-')) {
是不是可以扩充一下 amis-core里的generateIcon

2022-08-09 03:13 UTC, tooeast commented on packages/amis/src/renderers/Icon.tsx
> +    if (icon && typeof icon === 'string' && icon.startsWith('svg-')) {
有扩充

2022-10-10 09:58 UTC, merged