fix: 调整Tree组件判断展开收起的逻辑 (#4727)
baidu/amis pull request #5050
Opened 2022-08-02 13:32 UTC by meerkat-morecats

2022-08-03 11:43 UTC, lurunze1226 requested changes

2022-08-03 11:43 UTC, lurunze1226 commented on packages/amis-ui/src/components/Tree.tsx
> +  syncUnFolded(props: TreeSelectorProps, initial?: boolean) {
`syncUnFolded` 这个方法在外部的渲染器里有引用，不能直接修改

2022-08-03 11:43 UTC, lurunze1226 commented on packages/amis-ui/src/components/Tree.tsx
> +    const {valueField} = this.props;
从参数的props里获取

2022-08-03 11:43 UTC, lurunze1226 commented on packages/amis-ui/src/components/Tree.tsx
> +    for (const key of Array.from(this.unfolded)) {
`Array.from` ie11不支持，看看编译后是否有Polyfill

2022-08-11 11:06 UTC, meerkat-morecats commented on packages/amis-ui/src/components/Tree.tsx
> +    const {valueField} = this.props;
> 从参数的props里获取

那里取得不准了

2022-08-11 12:11 UTC, meerkat-morecats commented on packages/amis-ui/src/components/Tree.tsx
> +    const {valueField} = this.props;
> > 从参数的props里获取
> 
> 那里取得不准了

看起来也不是，忘记了为啥要这样改了

2023-02-01 08:49 UTC, closed without merging