feat: 只有最外层组件的loading可以生效
baidu/amis pull request #5096
Opened 2022-08-09 08:33 UTC by meerkat-morecats

fix: #5026

2022-08-11 03:39 UTC, qianxiaofendou commented on packages/amis-core/src/store/form.ts
> -      get loading() {
zheli

2022-08-11 04:50 UTC, meerkat-morecats commented on packages/amis-core/src/store/form.ts
> -      get loading() {
> 这里删除了`loading`属性，在`/packages/amis/src/renderers/Wizard.tsx`里面的下面的代码：
> 
> ```
> render(
>   'body',
>   {
>     ...step,
>     type: 'form',
>     ...
>   },
>   {
>     ...
>     onQuery: this.handleQuery,
>     disabled: store.loading,
>     popOverContainer:
>       popOverContainer || this.getPopOverContainer,
>     onChange: this.handleChange,
>     formStore: undefined
>   }
> )
> ```
> 
> 存在一种场景，表单里面有个按钮，点击之后会去获取数据，这时候整个表单是`disabled`的状态，这个是很有用的，现在改了之后上面的`store.loading`是不是就不能使用了，其它使用到表单的地方(dialog等)是否会受到影响？

formStore 继承自 serviceStore，在 serviceStore 中有通用的逻辑来处理 loading

2022-08-11 05:23 UTC, qianxiaofendou commented on packages/amis-core/src/store/form.ts
> -      get loading() {
好的，感谢大佬的优化！

2022-08-11 11:35 UTC, lurunze1226 requested changes

2022-08-11 11:35 UTC, lurunze1226 commented on examples/components/Dialog/Simple.jsx
> +    {
CRUD和Dialog这两个单独放一个文件里吧，把不同情况下的loading demo演示一下

2022-08-11 11:35 UTC, lurunze1226 commented on mock/index.js
> +      setTimeout(() => {
别直接改这个，单独出一个测试loading的接口

2022-08-11 11:35 UTC, lurunze1226 commented on packages/amis-core/src/store/form.ts
> -      get loading() {
这个不能直接干掉

2022-08-11 11:35 UTC, lurunze1226 commented on packages/amis/src/renderers/CRUD.tsx
> +const CRUDRenderer = Renderer({
这些渲染器应该在SchemaRenderer里通过白名单统一包装，不然每个组件还要单独处理

2022-08-12 09:09 UTC, meerkat-morecats commented on packages/amis-core/src/withShowLoading.tsx
> +        computedLoading = showLoading && loading;
现在方案：props.showLoading && props.loading 共同决定当前组件是否需要进入 loading 状态

若改为只有一个 loading 来判断的话，那么在父组件 loading 结束时，子组件的判断条件应该是 childLoading = !props.loading = true，会是一个问题

2022-08-25 09:56 UTC, 2betop approved these changes

2022-08-25 10:00 UTC, merged