feat: table 上增加新的属性 height 来配置 autoFillHeight == true 时的 table 高度
baidu/amis pull request #5147
Opened 2022-08-16 06:32 UTC by meerkat-morecats

2022-08-29 03:17 UTC, lurunze1226 requested changes

2022-08-29 03:17 UTC, lurunze1226 commented on packages/amis/src/renderers/Table/index.tsx
> +  height?: number;
这个作为autoFillHeight的子属性吧，不然容易被人误解，如果autoFillHeight设置了height属性才生效

2022-08-29 03:17 UTC, lurunze1226 commented on packages/amis/src/renderers/Table/index.tsx
> +  // itemBadge?: BadgeObject;
这些为什么要干掉？

2022-08-29 04:44 UTC, meerkat-morecats commented on packages/amis/src/renderers/Table/index.tsx
> +  // itemBadge?: BadgeObject;
> 这些为什么要干掉？

TableSchema 在 TableSchema 中有了，这个 interface 增加了多继承

2022-09-01 12:09 UTC, lurunze1226 approved these changes

2022-09-01 12:10 UTC, merged