Feat/form pure submit
baidu/amis pull request #5326
Opened 2022-09-06 09:09 UTC by pianruijie

支持pureSubmit事件

2022-09-06 09:29 UTC, hsm-lv requested changes

2022-09-06 09:29 UTC, hsm-lv commented on packages/amis-core/src/renderers/Form.tsx
> +    const pureSubmitEvent = $schema?.onEvent?.pureSubmit;
需要check一下pureSubmitEvent有没有绑动作

2022-09-29 10:51 UTC, 2betop commented on examples/components/EventAction/cmpt-event-action/FormEvent.jsx
> +      body: [
如果不做这些，那为何要叫做 submit

2022-09-29 10:53 UTC, 2betop commented on packages/amis-core/src/renderers/Form.tsx
> +    if (dispatcher?.prevented || submitEvent) {
第二个判断感觉不需要，而且这个地方不应该读取 $schema 变量

2022-11-15 13:51 UTC, 2betop approved these changes

2022-11-16 03:22 UTC, hsm-lv approved these changes

2022-11-16 03:41 UTC, merged