fix: 修复 crud 导出时会导出首列-操作列
baidu/amis pull request #5333
Opened 2022-09-07 11:42 UTC by meerkat-morecats

2022-09-15 11:39 UTC, lurunze1226 requested changes

2022-09-15 11:39 UTC, lurunze1226 commented on packages/amis/src/renderers/Table/exportExcel.ts
> +      ? columns.filter(column => {
这个直接取store.getColumnsExceptBuiltinTypes就可以了吧？过滤掉内置的和不可见的列

2022-09-29 05:46 UTC, nwind commented on packages/amis-core/src/store/table.ts
> +      console.log(self.columns);
删了

2022-10-12 07:27 UTC, lurunze1226 approved these changes

2022-10-12 07:28 UTC, merged