feat: 表单项增加展示态
baidu/amis pull request #5391
Opened 2022-09-19 06:42 UTC by CheshireJCat

### 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [x] 功能增强
- [ ] 国际化语料改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 其他改动（是关于什么的改动？）

### 需求背景和解决方案
表单输入态展示态切换
https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/CB1YWGgjJB3DYZ

### 更新日志

以下表单项支持展示态：
- 数字输入框
- textarea输入框
- 单选
- 多选
- 勾选
- 下拉列表
- 按钮选择器
- 标签选择器
- 城市选择器
- 时间选择类表单项
- 时间范围选择类表单项
- 列表选择器
- 滑块
- 评分
- 矩阵输入框
- combo
- inputKv
- inputKvs
- 树选择器
- 级联选择器
- 穿梭器

之前已支持的表单项
- 文本输入框
- 颜色选择器
- switch

### 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-10-13 12:38 UTC, lurunze1226 requested changes

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis-core/src/renderers/Item.tsx
> +  staticSchema?: any;
感觉这些属性可以放在同一个object中？
```
{
    staticConfig: {
        className?: string;
        ....
    }
}
```

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis-ui/src/components/BaiduMapPicker.tsx
> +          (typeof this.props?.onChange === 'function') && this.props?.onChange({
后面的不需要写`?.`

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/ChartRadios.tsx
> +        this.highlight(this.props.options.indexOf(this.props.selectedOptions[0]));
多了空行，格式化处理一下

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/ChainedSelect.tsx
> +          return selectedOption[labelField] || value;
这个不应该使用`||`，因为label可能就是0或者false

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/ChainedSelect.tsx
> +        .filter(v => v !== null)
`!= ` 过滤掉`undefined`

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/StaticHoc.tsx
> +        return label || value
这种建议再确定一下，如果有的缺少label，有的缺少value，那结果可能会让用户很疑惑

2022-10-13 12:38 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/Textarea.tsx
> +        {displayValue.split('\n').map((text: string, index: number) => {
文本会不会溢出？

2022-10-14 04:57 UTC, CheshireJCat commented on packages/amis-core/src/renderers/Item.tsx
> +  staticSchema?: any;
目前form只支持 static、staticClassName
formItems 支持 static、staticClassName、staticLabelClassName、staticInputClassName、staticSchema
后续这些属性会作为schema的配置属性，为了统一，放在外层比较好

2022-10-18 13:13 UTC, 2betop requested changes

2022-10-18 13:13 UTC, 2betop commented on packages/amis/src/renderers/Words.tsx
> +    console.log(words, this.props);
删掉

2022-10-18 13:13 UTC, 2betop commented on packages/amis/src/renderers/Form/StaticHoc.tsx
> +
这代码格式有点与众不同，没有经过 prettier 处理？

2022-10-19 01:36 UTC, 2betop approved these changes

2022-10-19 01:37 UTC, merged