fix: crud toolbar data同步更新问题修复
baidu/amis pull request #5431
Opened 2022-09-23 06:23 UTC by wanglinfang2014

2022-11-04 05:51 UTC, lurunze1226 requested changes

2022-11-04 05:51 UTC, lurunze1226 commented on packages/amis-core/src/store/table2.ts
> -      config.maxKeepItemSelectionLength !== void 0 &&
这里的变量还会用到https://sourcegraph.com/github.com/baidu/amis/-/blob/packages/amis-core/src/store/table.ts?L721

2023-03-17 11:17 UTC, wanglinfang2014 commented on packages/amis-core/src/store/table2.ts
> -      config.maxKeepItemSelectionLength !== void 0 &&
因为table2的实现方式不太一样，所以store里不需要这两个配置了

2023-05-05 03:17 UTC, 2betop approved these changes

2023-05-05 03:21 UTC, lurunze1226 approved these changes

2023-05-05 03:21 UTC, merged