fix: input-table 内部校验问题
baidu/amis pull request #5518
Opened 2022-10-10 11:06 UTC by tooeast

2022-10-18 12:24 UTC, lurunze1226 requested changes

2022-10-18 12:24 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    );
不需要return result吗？

2022-10-24 06:34 UTC, tooeast commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    );
不需要的，

2022-10-24 06:35 UTC, lurunze1226 approved these changes

2022-10-24 06:36 UTC, merged