fix: picker 内联模式默认值问题
baidu/amis pull request #5563
Opened 2022-10-14 10:27 UTC by tooeast

2022-10-14 11:46 UTC, 2betop commented on packages/amis-core/src/renderers/wrapControl.tsx
> +            const oldValue = this.model.value;
不在 form 里面会有问题，应该尽量避免使用 this.model.value

2022-10-18 12:19 UTC, lurunze1226 requested changes

2022-10-18 12:19 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/Picker.tsx
> +                .map(item => item.id)
这里应该使用CRUD的`primaryField`字段，用户可能通过Picker设置该字段，在Picker中应该是`valueField`

2022-10-24 06:46 UTC, lurunze1226 approved these changes

2022-10-24 06:47 UTC, merged