Update date.md
baidu/amis pull request #5569
Opened 2022-10-17 06:30 UTC by WangXueZhi

valueformat -> valueFormat

2022-10-18 12:11 UTC, lurunze1226 requested changes

2022-10-18 12:11 UTC, lurunze1226 commented on docs/zh-CN/components/date.md
> +如果你的数据值默认不是`X`格式（时间戳秒格式），那么需要配置 `valueFormat `参数用于解析当前时间值，比如毫秒是配置 `"valueFormat": "x"`。
`valueFormat `参数用 多个一个空格

2022-10-18 12:13 UTC, lurunze1226 commented on docs/zh-CN/components/date.md
> +如果你的数据值默认不是`X`格式（时间戳秒格式），那么需要配置 `valueFormat `参数用于解析当前时间值，比如毫秒是配置 `"valueFormat": "x"`。
顺便改一下PR的标题吧`docs: 修复Date日期组件文档错误...`

2022-10-21 08:52 UTC, nwind approved these changes

2022-10-21 08:54 UTC, merged