feat: 事件动作支持变量赋值
baidu/amis pull request #5585
Opened 2022-10-18 08:52 UTC by lurunze1226

2022-10-20 02:21 UTC, 2betop requested changes

2022-10-20 02:21 UTC, 2betop commented on packages/amis-core/src/variables.ts
> +export const variableMap: Record<string, VariableConfig> = {};
目前看跟 store，跟 schemaRenderer 深度关联。而 store 并不是全局级别，这里缺是全局级别，有点对不上号。

并不是所有的 amisRenderer 都会传相同的数据，目前这影响范围有点多。

2022-10-20 02:21 UTC, 2betop commented on packages/amis-core/src/variables.ts
> +export const variableMap: Record<string, VariableConfig> = {};
最好是下发属性，从 props 取变量信息

2022-10-24 02:05 UTC, hsm-lv requested changes

2022-10-24 02:05 UTC, hsm-lv commented on packages/amis-core/src/actions/Action.ts
> +  componentId?: string | string[]; // 组件ID，用于直接执行指定组件的动作
多个的话逗号分隔就行

2022-10-24 02:05 UTC, hsm-lv commented on packages/amis-core/src/actions/CmptAction.ts
> +    if (action.actionType === 'setVariable') {
对于组件来说，变量更新等于数据域的更新，和现在的setValue有些重复，可以融合一下，但应该不需要新增一种动作

2022-10-24 02:05 UTC, hsm-lv commented on packages/amis-core/src/variables.ts
> + * @file 全局变量相关
可以考虑与现有数据域机制做一个打通？

2022-11-17 01:36 UTC, 2betop commented on packages/amis-core/src/index.tsx
> +export const version = `__buildVersion`;
这里不能用 ``, replace 插件貌似只识别 '__buildVersion'

2022-11-17 01:55 UTC, 2betop commented on packages/amis-core/src/SchemaRenderer.tsx
> +    /** 变量更新后处理上层数据域的更新，Form中的组件可以通过事件动作更新，所以过滤掉 */
没必要每个 Renderer 都处理吧，直接 Root.tsx 里面处理？另外直接放在原型链上也能满足吧?

2022-11-17 02:00 UTC, 2betop commented on packages/amis-core/src/actions/CmptAction.ts
> +    if (action.actionType === 'setVariable') {
+1

2022-11-17 02:09 UTC, 2betop commented on packages/amis-core/src/store/variable.ts
> +    schema: types.optional(types.frozen(), undefined),
叫 jsonschema 把，要不好晕

2023-01-03 12:30 UTC, 2betop approved these changes

2023-01-04 01:57 UTC, hsm-lv approved these changes

2023-01-04 01:57 UTC, merged