fix: 添加submit事件，补充Form校验逻辑
baidu/amis pull request #5598
Opened 2022-10-20 06:56 UTC by RickCole21

2022-10-20 12:33 UTC, lurunze1226 approved these changes

2022-10-20 12:35 UTC, lurunze1226 requested changes

2022-10-20 12:35 UTC, lurunze1226 commented on packages/amis-core/src/actions/AjaxAction.ts
> +      const valid = await store.validate();
这里会漏掉Form中`action.required`的校验吧

2022-10-24 07:45 UTC, RickCole21 commented on packages/amis-core/src/actions/AjaxAction.ts
> +      const valid = await store.validate();
这个 action 应该是事件动作中的 action，目前没支持在action上配置required，要支持应该是另外的pr了

2022-10-24 08:05 UTC, hsm-lv requested changes

2022-10-24 08:05 UTC, hsm-lv commented on packages/amis-core/src/actions/AjaxAction.ts
> +    if (
AajaxAction是比较基础的http请求动作，不包含业务逻辑，所以不应该在这里面加submit相关的逻辑

2022-10-25 08:02 UTC, closed without merging