feat: List组件支持itemClick事件; chore: Picker组件事件名称修正为驼峰格式
baidu/amis pull request #5620
Opened 2022-10-24 13:05 UTC by lurunze1226

2022-10-24 13:34 UTC, hsm-lv requested changes

2022-10-24 13:34 UTC, hsm-lv commented on docs/zh-CN/components/list.md
> +`2.4.0`版本后，建议使用[事件动作](../../docs/concepts/event-action)处理组件事件，支持更多触发动作。`itemAction`和`onEvent`同时配置时会先执行`onEvent`，再执行`itemAction`，如果`onEvent`中配置了[阻止组件默认行为](../../../examples/action/prevent/form)，则执行完动作
这个还是写到示例里合适？，如果想特意强调这个事件，就在事件表那里着重说明一下，然后链接过去

2022-10-24 13:34 UTC, hsm-lv commented on packages/amis/src/renderers/List.tsx
> +      createObject(item.data, {
createObject(this.props.data, {item})

2022-10-24 13:34 UTC, hsm-lv commented on packages/amis/src/renderers/List.tsx
> +      const prevent = await onClick?.(e, item);
这个没太懂，为什么直接跟下面一样走onAction

2022-10-25 07:38 UTC, lurunze1226 commented on packages/amis/src/renderers/List.tsx
> +      createObject(item.data, {
这个是点击单行行为，感觉super里应该是当前行所在的数据域？

2022-10-25 07:39 UTC, lurunze1226 commented on packages/amis/src/renderers/List.tsx
> +      const prevent = await onClick?.(e, item);
这里是为了兼容`itemAction的`逻辑

2022-10-25 07:40 UTC, lurunze1226 commented on docs/zh-CN/components/list.md
> +`2.4.0`版本后，建议使用[事件动作](../../docs/concepts/event-action)处理组件事件，支持更多触发动作。`itemAction`和`onEvent`同时配置时会先执行`onEvent`，再执行`itemAction`，如果`onEvent`中配置了[阻止组件默认行为](../../../examples/action/prevent/form)，则执行完动作
OK

2022-10-25 10:47 UTC, hsm-lv requested changes

2022-10-25 10:47 UTC, hsm-lv commented on packages/amis/src/renderers/List.tsx
> +      const prevent = await onClick?.(e, item);
直接复用itemAction好了，不新增onClick这个东西了，这里发现hasClickActions就直接调用itemAction，然后list那层去处理itemAction

2022-10-26 01:44 UTC, hsm-lv approved these changes

2022-10-26 01:44 UTC, merged