tree 虚拟列表
baidu/amis pull request #5696
Opened 2022-11-04 06:11 UTC by meerkat-morecats

2022-11-09 03:19 UTC, lurunze1226 requested changes

2022-11-09 03:19 UTC, lurunze1226 commented on packages/amis-ui/src/components/virtual-list/index.tsx
> +    this.forceUpdate();
这个太粗暴了，会导致多次无效渲染的

2022-11-09 03:19 UTC, lurunze1226 commented on packages/amis-ui/src/components/Tree.tsx
> +import merge from 'lodash/merge';
没用到就不需要引入了

2022-11-09 03:38 UTC, meerkat-morecats commented on packages/amis-core/src/renderers/Item.tsx
> +    model?.filteredOptions;
> 这个调用没看懂，如果是为了监听变化，应该在reaction里处理

不是为了监听变化，不把这一行放在这里，这个 options变化的时候，组件不会render

2022-11-11 09:29 UTC, meerkat-morecats commented on packages/amis-ui/src/components/virtual-list/index.tsx
> +    this.forceUpdate();
> 这个太粗暴了，会导致多次无效渲染的

看了看，这也没啥更好的办法呀

2022-11-23 01:52 UTC, lurunze1226 approved these changes

2022-11-23 01:52 UTC, merged