feat: input-table组件新增事件和动作
baidu/amis pull request #6078
Opened 2023-01-16 10:37 UTC by DynaZhang

1. input-table组件新增事件和动作
2. 表格右侧的操作栏“图标”放在“文字”左边
3. 支持静态展示(static)
4. 补充文档

2023-01-17 03:58 UTC, hsm-lv requested changes
按照演示评审结论改下先

2023-01-18 02:55 UTC, DynaZhang commented
1. 现有组件数据 -> 表格数据
2. updateApi、updateSuccess、updateFail -> editApi、editSuccess、editFail
3. 优化事件携带的参数
4. 文档更新

2023-01-20 08:50 UTC, hsm-lv requested changes

2023-01-20 08:50 UTC, hsm-lv commented on examples/components/EventAction/cmpt-event-action/InputTableEventAction.jsx
> +      "label": "combo赋值",
是不是和上面按钮混淆了，上面的啥也没干，label是对的

2023-01-20 08:50 UTC, hsm-lv commented on examples/components/EventAction/cmpt-event-action/InputTableEventAction.jsx
> +              "componentId": "u:d8819450ebba",
缺少一个指定index的setValue

2023-01-20 08:50 UTC, hsm-lv commented on examples/components/EventAction/cmpt-event-action/InputTableEventAction.jsx
> +                msg: '触发add ${event.data.value|json}'
demo里面尽量用name来获取值吧，其实event.data.value只是一个最保险的拿值方式

2023-01-20 08:50 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +  editApi?: SchemaApi;
breakchange!!!

2023-01-20 08:50 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    switch(action.actionType) {
这里不拆分case了，其实都是对值的修改，分开反而不好阅读

2023-01-20 08:50 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    const value = map(cloneDeep(items), item => {
直接items.map?

2023-01-20 08:50 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +            // TODO: 这里是为了处理里使用value变量添加的，目前会影响初始化数据加载后的组件行为，先回滚
?

2023-01-20 08:50 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +          !!!isStatic &&
?，一个非就够了？

2023-02-16 12:35 UTC, hsm-lv requested changes

2023-02-17 08:07 UTC, closed without merging