feat: input-table添加事件动作
baidu/amis pull request #6308
Opened 2023-03-07 02:55 UTC by DynaZhang

2023-03-10 06:54 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> -    if (action.actionType === 'add') {
加个 || 不能有 breakchange

2023-03-10 06:55 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> -      action.actionType === 'remove' ||
+1

2023-03-20 03:05 UTC, 2betop requested changes
@hsm-lv 也一起review一下

2023-03-20 03:05 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        })
原来的 action.payload 逻辑需要考虑兼容

2023-03-20 03:05 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        const payload = await env.fetcher(deleteApi, deleteItem);
action.payload 逻辑需要考虑兼容

2023-03-20 03:05 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    if (rendererEvent?.prevented) {
这个逻辑貌似没啥用，代码起不到预期的效果

2023-03-21 06:07 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +            items.splice(i + pushIndex, -1, toAdd[i]);
-1的含义是添加一项，这里主要是支持 在指定位置插入数据

2023-03-21 06:43 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +            items.splice(i + pushIndex, -1, toAdd[i]);
第二个参数 是 0 或者负数，则不移除元素，这种情况下至少添加一个元素。这里主要是满足在指定位置添加数据的场景。然后这个参数我会改成0，和其他保持一致

2023-03-21 07:37 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> -    if (action.actionType === 'add') {
因为老action执行的逻辑较为复杂，所以讲原先的action保留，新增的action会基于else if添加

2023-03-21 07:38 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +      if (addApi || args) {
因为老action执行的逻辑较为复杂，所以将原先的action保留，新增的action会基于else if往后添加

2023-03-21 07:39 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        })
同上

2023-03-21 07:39 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        const payload = await env.fetcher(deleteApi, deleteItem);
同上

2023-03-23 08:17 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +      const items = cloneDeep(this.state.items);
直接 concat 就够了吧，为何要深拷贝

2023-03-23 08:18 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> -      if (addApi || action.payload) {
action.payload 不等价于 args 啊，依然存在不兼容问题

2023-03-25 07:21 UTC, hsm-lv requested changes

2023-03-25 07:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +      if (args.condition) {
删除肯定是index优先

2023-03-25 07:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +          const flag = evalExpression(args?.condition, {record: item, rowIndex});
这里表达式的数据不对，之类应该是直接是record+index，{...record, rowIndex}

2023-03-25 07:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +      delete item.__isPlaceholder;
这个感觉删不删不重要，可以不处理

2023-03-25 07:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    let isPrevented = await this.dispatchEvent(confirmEventName, {index: this.state.editIndex, item});
const

2023-03-25 07:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +      items[pushIndex] = value;
const items = [...this.state.items];
// 用splice语义更清晰
items.splice(index, 1, value);
this.setState({items: items})

2023-03-27 03:36 UTC, DynaZhang commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    let isPrevented = await this.dispatchEvent(confirmEventName, {index: this.state.editIndex, item});
这里用let是因为下面有重新赋值的逻辑
let isPrevented = await this.dispatchEvent(confirmEventName, {index: this.state.editIndex, item});

isPrevented = await this.dispatchEvent(successEventName, {index: this.state.editIndex, item});

2023-04-06 03:03 UTC, hsm-lv requested changes

2023-04-06 03:03 UTC, hsm-lv commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    ctx: RendererData,
这里的第二个参数应该只会有动作参数args

2023-04-06 12:56 UTC, hsm-lv requested changes

2023-04-06 12:56 UTC, hsm-lv commented on examples/components/EventAction/cmpt-event-action/InputTableEvent.jsx
> +              "payload": {
参数结构不对，另外你确定你改完之后用这个demo跑过了吗

2023-04-07 03:21 UTC, hsm-lv approved these changes

2023-04-10 06:43 UTC, 2betop requested changes

2023-04-10 06:43 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +    if (isPrevented) {
我觉得这个事件不需要再支持 prevent 了 addSuccess 和 editSuccess 一看都是已完成时了

2023-04-10 06:43 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        for (let i = 0; i < args.item.length; i++) {
往里面插入东西，这个 for 应该从右到左，而不是从左到右，因为左边插入了新东西，会影响右边的位置

2023-04-10 06:43 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
> +        items.forEach(async (item, rowIndex) => {
forEach 里面写 async 方法会有时序问题？并不会按顺序执行的，而且外面并没有等里面的循环结束就会继续往吓跑，可能还没判断完，就已经 this.setState 了

2023-04-10 06:43 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTable.tsx
>        }
deleteSuccess 呢？

2023-04-11 08:47 UTC, 2betop approved these changes

2023-04-11 08:51 UTC, merged