feat: 为 tag 和 each 补充事件动作
baidu/amis pull request #6325
Opened 2023-03-08 13:09 UTC by meerkat-morecats

2023-03-09 03:51 UTC, lurunze1226 requested changes

2023-03-09 03:51 UTC, lurunze1226 commented on packages/amis/src/renderers/Tag.tsx
> +        nativeEvent,
事件不需要抛出来了

2023-03-09 07:26 UTC, meerkat-morecats commented on packages/amis/src/renderers/Tag.tsx
> +        nativeEvent,
> 事件不需要抛出来了

得抛出去吧，万一有单独用的场景那个删除的tag就没用了

2023-03-09 07:27 UTC, meerkat-morecats commented on packages/amis/src/renderers/Tag.tsx
> +        nativeEvent,
> 事件不需要抛出来了

得抛出去吧，万一有单独用的场景那个删除的tag就没用了

2023-03-15 07:17 UTC, lurunze1226 approved these changes

2023-03-15 07:17 UTC, merged