fix: 修复table同时具备 fixed group 时，表头无法和内容列对应
baidu/amis pull request #6466
Opened 2023-03-24 09:38 UTC by meerkat-morecats

2023-03-28 07:10 UTC, lurunze1226 requested changes

2023-04-04 05:44 UTC, meerkat-morecats commented on packages/amis/src/renderers/Table/index.tsx
> +        )}px;table-layout: fixed;`;
之前我加的这个，现在看着比较丑，就把他删了

2023-04-04 05:48 UTC, meerkat-morecats commented on packages/amis/src/renderers/Table/index.tsx
> -      ?.getBoundingClientRect()?.height;
> 这里为啥要删除，固定列的表头可能会错位

这个是同步高度的

2023-04-04 05:48 UTC, meerkat-morecats commented on packages/amis/src/renderers/Table/index.tsx
> +        )}px;table-layout: fixed;`;
> 这个不能一概而论吧

这个因为前边的width都是有的，其实可以弄成fixed

2023-05-08 06:41 UTC, closed without merging