feat: Button-group-select支持统一配置所有选项角标
baidu/amis pull request #6506
Opened 2023-03-31 03:33 UTC by Dora-boots

1、支持button-group-select统一配置角标
2、支持option中配置角标，可覆盖统一配置
3、支持外层配置角标后，option中仅配置角标文案

2023-04-14 03:40 UTC, lurunze1226 requested changes

2023-04-14 03:40 UTC, lurunze1226 commented on vite.config.ts
> +import { defineConfig } from 'vite';
格式化处理一下

2023-04-14 03:40 UTC, lurunze1226 commented on packages/amis-editor/src/renderer/OptionControl.tsx
> +                onChange: (v: string) => this.toggleBadge(index, v)
toggleBadge接受的参数类型没改

2023-04-14 03:40 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/ButtonGroupSelect.tsx
> +            : option?.badge
这里应该判断是否为对象，因为badge可能为数字

2023-04-14 03:40 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/ButtonGroupSelect.tsx
> +          : button.badge;
这个和上面的方法是一样的吧，可以统一一个方法

2023-04-18 05:58 UTC, lurunze1226 approved these changes

2023-04-18 06:03 UTC, igrowp approved these changes

2023-04-23 12:58 UTC, merged