feat: crud、crud2支持行移入、行移出事件
baidu/amis pull request #6507
Opened 2023-03-31 03:50 UTC by wanglinfang2014

2023-04-07 05:39 UTC, hsm-lv requested changes

2023-04-07 05:39 UTC, hsm-lv commented on packages/amis/src/renderers/Cards.tsx
> +// 事件调整 对应CRUD里的事件配置也需要同步修改
这个调整有breakchange吗

2023-04-07 05:39 UTC, hsm-lv commented on packages/amis/src/renderers/Table/TableRow.tsx
> +        rowItem: item?.data,
目前input-table参数名字为item、index，看是否统一一下

2023-04-17 06:26 UTC, hsm-lv approved these changes

2023-04-17 11:39 UTC, 2betop approved these changes

2023-04-18 01:34 UTC, merged