feat: wizard组件样式交互改造
baidu/amis pull request #6596
Opened 2023-04-13 02:49 UTC by DynaZhang

1. wizard组件步骤条换成amis-ui的steps组件
2. amis-ui的steps组件支持onClickStep事件，支持wizard组件点击步骤后跳转
3. wizard支持withWrapPanel属性（是否包含panel边框，同form组件的withWrapPanel）
4. amis-ui支持不同区域的样式配置：stepsClassName（步骤条区域样式）、stepClassName（除去底部操作栏区域样式）、bodyClassName（表单区域样式）、footerClassName（底部操作栏样式）
5. wizard组件支持动态步骤

2023-05-06 01:50 UTC, 2betop requested changes

2023-05-06 01:50 UTC, 2betop commented on packages/amis/src/renderers/Wizard.tsx
> +          title: step.title || step.label || `第${index + 1}步`
文案没有经过 locale 转换

2023-05-06 01:50 UTC, 2betop commented on packages/amis/src/renderers/Wizard.tsx
> +    this.normalizeSteps(values);
这里应该是穿 final ？

2023-05-06 01:50 UTC, 2betop commented on packages/amis/src/renderers/Wizard.tsx
> +    const steps = this.props.steps;
如果 steps 或者上下文数据变化了，没有看到同步 state.rawSteps 的相关逻辑。

2023-05-08 06:19 UTC, DynaZhang commented on packages/amis/src/renderers/Wizard.tsx
> +    const steps = this.props.steps;
steps发生变化，就在componentDidUpdate监听

2023-05-08 06:43 UTC, 2betop commented on packages/amis/src/renderers/Wizard.tsx
> +    const steps = this.props.steps;
上下文变化也是在 didUpdate 里面，setData 只是修改上下文数据的一个途径，不是所有的修改都是走 setData 来的。

2023-05-08 10:34 UTC, 2betop approved these changes

2023-05-09 01:35 UTC, hsm-lv approved these changes

2023-05-09 01:35 UTC, merged