amis-saas-9246 feat: input-table接入事件动作面板
baidu/amis pull request #6612
Opened 2023-04-14 02:12 UTC by DynaZhang

2023-05-06 02:03 UTC, igrowp commented on packages/amis-editor/src/plugin/Form/InputTable.tsx
> +            name: '__deleteType',
变量为什么要加 __

2023-05-23 08:50 UTC, DynaZhang commented on packages/amis-editor/src/plugin/Form/InputTable.tsx
> +            name: '__deleteType',
变量名加上”__“之后可以不在schema中出现。这个变量只是控制下面控件的显隐，没有必要在schema中展示

2023-05-23 13:06 UTC, hsm-lv requested changes

2023-05-24 10:27 UTC, hsm-lv requested changes

2023-05-24 10:27 UTC, hsm-lv commented on packages/amis-editor/src/plugin/Form/InputTable.tsx
> +              title: '添加项数据'
新增行记录

2023-05-24 10:27 UTC, hsm-lv commented on packages/amis-editor/src/plugin/Form/InputTable.tsx
> +              title: '添加项的行索引'
新增行记录索引

2023-05-31 04:03 UTC, hsm-lv requested changes

2023-05-31 07:19 UTC, hsm-lv approved these changes

2023-05-31 07:36 UTC, merged