feat:确认对话框支持schema配置
baidu/amis pull request #6703
Opened 2023-04-24 11:18 UTC by ascend13

1.确认对话框内容区支持配置schema
2.弹框支持配置大小
3.按钮支持配置样式

2023-05-05 12:54 UTC, 2betop commented
目前 ci 有报错，请重新同步一下上游再试

2023-05-12 02:10 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +    if (dialogType === 'confirm') {
逻辑重复了，有 confirm 属性在 buildActions 会自动构建取消和确认按钮，另外你这个 button 事件都绑定，完全是摆设

2023-05-12 03:25 UTC, ascend13 commented on packages/amis/src/renderers/Dialog.tsx
> +    if (dialogType === 'confirm') {
这里的confirm是传入的一个类型用来区分普通弹框和确认弹框，这两个button是renderer里来预览按钮的样式，实际上走的是alert的component，因此没有绑定事件
![image](https://github.com/baidu/amis/assets/25900057/c02552ca-f563-4444-95b2-8861cfbd6673)

2023-05-15 03:21 UTC, 2betop commented on packages/amis-ui/src/components/Alert.tsx
> +    cancelText?: string,
这个地方能否做个收纳，目前参数太多了，改成如下形式，不过需要兼容旧的调用方式。

confirm(content: string, title?: string, confirmText?: string, cancel?: string);
confirm(content: string, title?: string, options?: {
  confirmText?: stirng;
  cancelText?: string;
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full';
  closeOnEsc?: boolean;
  confirmBtnLevel?: string;
  cancelBtnLevel?: string;
});

2023-05-15 03:31 UTC, ascend13 commented on packages/amis-ui/src/components/Alert.tsx
> +    cancelText?: string,
好的我修改一下

2023-05-17 06:53 UTC, lurunze1226 requested changes

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-editor-core/scss/editor.scss
> +  &-footer {
类名有个typo，应该是`InlineModal`

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-editor/src/plugin/Dialog.tsx
> +      return getSchemaTpl('tabs', [
这里collapseGroup可以复用吧，通过开关控制一下body里的渲染项目

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-ui/src/components/Alert.tsx
> +  closeOnEsc?: boolean;
重复的props可以这样取`AlertProps['closeOnEsc']` `AlertProps['size']`

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-ui/src/components/Alert.tsx
> +        cancelBtnLevel: options?.cancelBtnLevel
options下的参数应该有个默认值？

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-core/src/actions/DialogAction.ts
> +  confirmDialog?: Schema; // 兼容历史
这个是新加的动作，还有必要单独放在confirmDialog里吗？可以直接取args

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis-editor/src/plugin/Dialog.tsx
> +        <div className="ae-InlineModel">
`InlineModal`统一更新一下吧

2023-05-17 06:53 UTC, lurunze1226 commented on packages/amis/src/renderers/Dialog.tsx
> +        confirmText={confirmText}
这里透传的属性是做什么的？confirm是用的Alert，这里的是Modal

2023-05-17 07:26 UTC, ascend13 commented on packages/amis/src/renderers/Dialog.tsx
> +        confirmText={confirmText}
这里是传给plugin识别confirmDialog的渲染项

2023-05-18 01:49 UTC, 2betop approved these changes

2023-05-18 03:09 UTC, hsm-lv requested changes

2023-05-18 03:09 UTC, hsm-lv commented on packages/amis-core/src/actions/DialogAction.ts
> +  confirmDialog?: Schema; // 兼容历史
放args里

2023-05-22 12:42 UTC, hsm-lv approved these changes

2023-05-30 13:03 UTC, lurunze1226 approved these changes

2023-05-30 13:03 UTC, merged