feat: collapse-group组件支持对外抛出 折叠状态改变 事件
baidu/amis pull request #7213
Opened 2023-06-19 03:20 UTC by DynaZhang

### What
collapse-group组件支持对外抛出 折叠状态改变 事件

### Why

需要拿到展开的折叠器对应的索引值以及是否折叠来实现业务，但现在collapse-group组件没有对外暴露 折叠状态改变 事件

### How
1. ui组件collapse-group支持对外抛出onCollapsedChange事件
2. renderer层collapse和collapse-group支持collapsedChange事件
3. 编辑器 collapse和collapse-group组件补充事件动作面板

2023-06-19 04:09 UTC, wibetter commented on packages/amis-ui/src/components/Collapse.tsx
> +    console.log('newCollapsed', newCollapsed);
多了一个console.log

2023-06-19 04:16 UTC, wibetter commented on packages/amis-ui/src/components/CollapseGroup.tsx
> +      activeKey.indexOf(collapseId) === -1
这里应该是 > -1 吧

2023-06-19 04:16 UTC, wibetter commented on packages/amis/src/renderers/Collapse.tsx
> +    console.log('collapsed', collapsed);
console.log需要删除

2023-06-19 04:21 UTC, DynaZhang commented on packages/amis-ui/src/components/CollapseGroup.tsx
> +      activeKey.indexOf(collapseId) === -1
这个地方是想 判断触发事件的折叠面板是否折叠。因为activeKey记录的是展开的折叠面板对应的索引值，所以这个地方通过判断是否等于-1来判断 面板是否折叠

2023-06-19 06:20 UTC, wibetter approved these changes

2023-06-19 06:43 UTC, lurunze1226 requested changes

2023-06-19 06:43 UTC, lurunze1226 commented on docs/zh-CN/components/collapse.md
> +折叠面板折叠状态改变时触发。
示例放在example 下面

2023-06-19 06:43 UTC, lurunze1226 commented on packages/amis-ui/src/components/Collapse.tsx
> +    props.onCollapse && props.onCollapse(props, newCollapsed);
onCollapse?.(newCollapsed)

2023-06-19 06:43 UTC, lurunze1226 commented on packages/amis-ui/src/components/CollapseGroup.tsx
> +      activeKey.indexOf(collapseId) === -1
这个为啥不能直接用函数入参的collapsed

2023-06-19 06:43 UTC, lurunze1226 commented on packages/amis/src/renderers/Collapse.tsx
> +      'collapsedChange',
应该是 collapseChange

2023-06-19 06:54 UTC, lurunze1226 requested changes

2023-06-19 06:54 UTC, lurunze1226 commented on docs/zh-CN/components/collapse.md
> +| collapsedChange | `activeKey: Array<string \| number>` 当前所有未折叠的折叠面板对应的索引值数组 <br /> `collapseId: string \| number` 触发事件的折叠面板对应的索引值 <br/> `collapsed: boolean` 触发事件的折叠面板是否折叠 | 折叠面板折叠状态改变时触发 |
应该是`collapseChange`，应该是名词 + change

2023-06-19 06:54 UTC, lurunze1226 commented on docs/zh-CN/components/collapse.md
> +### collapsedChange
示例放在 Example 下面吧

2023-06-19 06:54 UTC, lurunze1226 commented on packages/amis/src/renderers/CollapseGroup.tsx
> +  async onCollapsedChange(
func应该是 `handleCollapseChange`

2023-06-19 06:54 UTC, lurunze1226 commented on packages/amis/src/renderers/Collapse.tsx
> +  async onCollapsedChange(props: any, collapsed: boolean) {
func应该是 `handleCollapseChange`

2023-06-19 11:25 UTC, hsm-lv requested changes

2023-06-20 02:53 UTC, DynaZhang commented on packages/amis-ui/src/components/CollapseGroup.tsx
> +      activeKey.indexOf(collapseId) === -1
collapsed存储的是触发事件之前的状态，用来改变activeKey的值。所以这里用activeKey判断触发事件的折叠面板是否折叠更适合些

2023-06-20 12:08 UTC, hsm-lv requested changes

2023-06-20 12:08 UTC, hsm-lv commented on packages/amis-editor/src/plugin/CollapseGroup.tsx
> +                  title: '触发事件的折叠器对应的索引值'
折叠器索引

2023-06-20 12:08 UTC, hsm-lv commented on packages/amis-editor/src/plugin/CollapseGroup.tsx
> +                  title: '触发事件的折叠器是否折叠'
折叠器状态

2023-06-21 04:59 UTC, hsm-lv approved these changes

2023-06-30 05:55 UTC, lurunze1226 approved these changes

2023-06-30 05:55 UTC, merged