chore: 收敛时间组件format相关属性
baidu/amis pull request #7318
Opened 2023-06-30 03:53 UTC by Dora-boots

perf：时间相关组件format字段统一更替为 valueFormat(数据格式) / displayFormat(展示格式) ，避免同类字段过多增加用户学习成本

修改点：
一、AMIS组件修改
1、纯展示组件
【amis/render】：Date / DateRange 增加displayFormat 替代format，valueFormat维持不动
2、输入展示类组件
- 2.1 时间输入
- - 【Render】InputDate ｜ Input[Date / Month / Quarter / Year]Range ｜ Calendar | CalendarMobile 组件
   1)  Invariable： 默认值format / inputFormat维持不变
   2) delete： 删去timeFormat / dateFormat 默认值（控制日期选择框展示类型）
   3) change：向UI组件传参时 valueFormat 替换 format，且值为 valueFormat || format
- - 【UI】DatePicker ｜ DateRangePicker
   1) 传入Calendar组件的timeFormat / dateFormat 字段根据displayFormat进行判断
   2) 增加 displayFormat || inputFomrat / valueFormat || format 兼容旧版本字段，并优先支持新字段

二、Editor修改
将配置面板中 时间展示/值格式 对应的schema字段替换为新版本

三、补充单测
1、组件单测中使用的 inputFormat / format 部分更改为displayFormat / valueFormat
2、render组件使用的UI组件统一为 DatePicker / DateRangePicker，故针对两类组件分别选择了 inputDate.test.tsx / dateRange.test.tsx两个test文件，增加了新属性与原有属性兼容的测试case

四、补充文档
1、增加valueFormat / displatFormat属性（3.4.0版本支持）介绍，替换原有format / inputFormat介绍
2、示例中 值格式 / 展示格式等内容使用的 format / inputFormat 更改为新属性

2023-07-12 07:24 UTC, 2betop commented on packages/amis-ui/src/components/DatePicker.tsx
> +        (displayFormat || inputFormat)!
需要调用 `string2regExp` 处理一下，否则会可能出现正则转换错误，报错

2023-08-14 02:21 UTC, 2betop commented on packages/amis/__tests__/renderers/Form/__snapshots__/inputMonthRange.test.tsx.snap
> +                    class="rdt rdtStatic rdtOpen cxd-DateRangePicker-start"
这些确定不是 breakchange？

2023-08-14 02:23 UTC, 2betop commented on packages/amis/src/renderers/Form/InputQuarterRange.tsx
> +          format={valueFormat || format}
组件里面的名字是不是也应该一起换了

2023-08-14 02:23 UTC, 2betop commented on packages/amis/src/renderers/Form/InputYearRange.tsx
> +          format={valueFormat || format}
+1

2023-08-14 02:24 UTC, 2betop requested changes
请补充至少一个组件的兼容历史配置的用例

2023-08-23 08:08 UTC, 2betop approved these changes

2023-08-25 01:03 UTC, hsm-lv approved these changes

2023-08-25 01:03 UTC, merged