feat: 矩阵勾选MatrixCheckboxes功能增强
baidu/amis pull request #7425
Opened 2023-07-08 03:53 UTC by gaiyinaizhi

### What

1. 增加`yCheckAll`属性开启列上的全选功能
2. 增加`xCheckAll`属性开户行上的全选功能
3. 增加`textAlign`属性配置文本的对齐方式，开启多选功能时默认居左对齐

### Why

增强矩阵勾选功能，主要增加快捷的行/列全选能力

### How

修改表单能力的同时，同步修改编辑器中的属性配置能力及文档中的属性说明

2023-07-08 10:19 UTC, 2betop requested changes

2023-07-08 10:19 UTC, 2betop commented on packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> +    for (let i = 0; i < rows.length; i++) {
改成 array.some

2023-07-08 10:19 UTC, 2betop commented on packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> +      }
用个every比较合适，外加一个临时变量标记someChecked

2023-07-08 10:19 UTC, 2betop commented on packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> +      if (columns && columns[rowIndex] && columns[rowIndex].checked) {
array.some

2023-07-11 09:06 UTC, gaiyinaizhi commented on packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> +      if (columns && columns[rowIndex] && columns[rowIndex].checked) {
已调整，请帮忙检查

2023-07-12 07:20 UTC, 2betop commented
请补充相关的用例，用来验证功能是否符合预期

2023-07-13 02:42 UTC, 2betop approved these changes

2023-07-13 02:44 UTC, hsm-lv approved these changes

2023-07-13 03:06 UTC, merged

2023-07-13 03:09 UTC, gaiyinaizhi commented on packages/amis/src/renderers/Form/MatrixCheckboxes.tsx
> +    let checked = value[0][rowIndex].checked;
some方法就是要校验必须有checked状态不一致时才返回true，应该已经包含了后面加的非全选校验了吧~ 本地已经验证过这种场景了，有时间可以再看看~