feat: timeline组件支持detailClaaName/titleClassName/timeClassName & 可视化配置
baidu/amis pull request #7654
Opened 2023-08-01 12:48 UTC by Dora-boots

1、fix： 配置面板配置Timeline组件className不生效 
（原因：render/Timeline组件中未将props中的className传入Timeline UI组件）

2、feat:
- Timeline组件支持统一/单独配置节点detailClassName / timeClassName / titleClassName
- 配置面板支持统一配置detailClassName / timeClassName / titleClassName
- Timeline组件支持关联上下文

3、perf： 
- Timeline组件detail样式优化为自适应
- 补充Timeline组件文档

2023-08-02 03:43 UTC, lurunze1226 requested changes

2023-08-02 03:43 UTC, lurunze1226 commented on docs/zh-CN/components/timeline.md
> +| detailClassName | `string`                              |            | 统一配置的节点详情 CSS 类名                                 |
加一列，补充一下支持的版本

2023-08-02 03:43 UTC, lurunze1226 commented on docs/zh-CN/components/timeline.md
> +| detailClassName     | `string`                                                |           | 节点详情的 CSS 类名（优先级高于统一配置的 detailClassName） |
同上，补充一下支持的版本

2023-08-02 03:43 UTC, lurunze1226 commented on packages/amis-ui/scss/components/_timeline.scss
> +      .#{$ns}TimelineItem-content,
水平模式下还是要有一个最大宽度，或者自适应的最大宽度，detail 文字 key 用 word-break换行处理

2023-08-03 06:50 UTC, 2betop commented on packages/amis/src/renderers/Timeline.tsx
> +  const timelineItemsRow: Array<TimelineItemSchema> =
不应该下发 config 属性，而是 
<img width="778" alt="image" src="https://github.com/baidu/amis/assets/2698393/3fef65b1-96aa-439a-96af-355aa97121ec">
这就处理好

2023-08-03 09:55 UTC, 2betop approved these changes

2023-08-08 02:03 UTC, lurunze1226 approved these changes

2023-08-08 02:04 UTC, merged