feat: Dialog弹窗优化
baidu/amis pull request #7933
Opened 2023-08-24 12:43 UTC by ascend13

新版弹窗功能优化
* 弹窗设计从sub-editor弹出框的模式改为页面内可视化，新增弹窗设计视图
* 新增弹窗大纲和弹窗列表，罗列当前页面中有的所有弹窗
* 弹窗事件支持新建弹窗和选择现有弹窗
* 弹窗配置面板-属性优化
* 弹窗配置面板-外观配置优化

2023-08-29 03:50 UTC, 2betop commented on packages/amis-core/src/env.tsx
> +  ) => any;
什么地方用了这个？代码没搜到

2023-08-29 03:52 UTC, 2betop commented on packages/amis-core/src/utils/helper.ts
> +  childrenName?: string,
存在 breakchange，估计已有很多地方有 findTree，这直接修改搞不好原来的某些逻辑错误

2023-08-30 07:38 UTC, ascend13 commented on packages/amis-core/src/utils/helper.ts
> +  childrenName?: string,
已全局搜索所有使用到findTree的地方,对缺少了childrenName参数的地方添加了默认'children'参数

2023-09-01 08:55 UTC, 2betop commented on packages/amis-core/src/store/node.ts
>          callback?.();
为何要删掉这个？

2023-09-01 09:01 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +        for (let k in definitions) {
应该用 let of ， in 会遍历到原型链

2023-09-01 09:02 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +                if (item.actionType === 'dialog') {
为何不直接是 else if 呢

2023-09-01 09:06 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +    const dialogOptions = this.getDialogOutline();
每次都遍历，而不是 schema 发生变化的时候遍历？

2023-09-01 09:07 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +    const dialogOptions = this.getDialogOutline();
基于 store.schema 来个 computed 属性？

2023-09-01 09:09 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +    const Wrapper = inDesign ? Modal : wrapperComponent || Modal;
运行态不应该关注设计态的事

2023-09-01 09:11 UTC, 2betop commented on packages/amis-ui/src/components/Modal.tsx
> +  dialogClassName?: string;
这个组件叫 modal，应该事假 modalClassName?

2023-09-01 09:13 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +    let {hideActions, hideActionsOn, data} = this.props;
为何要有这个？actions 下发空数组不就行了？

2023-09-01 09:14 UTC, 2betop commented on packages/amis/src/renderers/Drawer.tsx
> +    let {hideActions, hideActionsOn, data} = this.props;
+1

2023-09-01 09:14 UTC, 2betop commented on packages/amis/src/renderers/Drawer.tsx
> +      'dialog-preview-mount-node'
+1

2023-09-01 09:20 UTC, 2betop commented on packages/amis-editor-core/src/component/Preview.tsx
> +          store.changeOutlineTabsKey('dialog-outline');
看起来像反模式

2023-09-01 09:21 UTC, 2betop commented on packages/amis-editor-core/src/component/RegionWrapper.tsx
> +      this.editorNode = this.parentNode.addDialogChild({
为何要区分来着？

2023-09-01 09:45 UTC, ascend13 commented on packages/amis/src/renderers/Dialog.tsx
> +    const Wrapper = inDesign ? Modal : wrapperComponent || Modal;
目的是想要设计弹窗的时候，弹窗是在画布中而不是在弹出到页面了，所以要修改弹窗的挂载位置，目前想到的方案就是传一个inDesign参数来区分场景挂载不同的地方

2023-09-04 03:19 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +    const Wrapper = inDesign ? Modal : wrapperComponent || Modal;
编辑器里面处理即可，不要调整运行态逻辑

2023-09-05 06:43 UTC, ascend13 commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +        for (let k in definitions) {
这里是对象来着

2023-09-06 03:32 UTC, lurunze1226 requested changes

2023-09-06 03:32 UTC, lurunze1226 commented on packages/amis/src/renderers/Dialog.tsx
> +    let {hideActions, hideActionsOn, data} = this.props;
+1

2023-09-06 07:06 UTC, lurunze1226 approved these changes

2023-09-06 08:40 UTC, 2betop commented on packages/amis-editor-core/src/component/Preview.tsx
> +    if (store.activeDialogPath) {
这个也应该来个 reeaction

2023-09-07 01:19 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +        if (option.type === 'drawer') {
这里可直接复用下面的 getDialogSchemaLable

2023-09-07 01:20 UTC, 2betop commented on packages/amis-editor-core/src/component/Panel/Outline.tsx
> +      this.props.store.changeOutlineTabsKey(key);
既然有 store 变量，就换一下位置，直接用 store 变量，且 changeOutLineTabsKey 同样需要 isAlive 判断，可直接跟 key 的判断放一起

2023-09-07 01:33 UTC, 2betop commented on packages/amis-editor-core/src/component/factory.tsx
> +}
以上方法存在副作用，同时完全没必要这么写，直接用现成方法就可以实现，大致思路是

```
const modal = JSONGetById(schema, dialogId);
if (modal) { // 如果通过 id 找到了
    const replacedSchema = JSONUpdate(schema, dialogId, {$ref: dialogRefsName}, true)
}
```

2023-09-07 01:38 UTC, 2betop commented on packages/amis-editor-core/src/component/factory.tsx
> +    definitions[dialogRefsName] = selectDialog;
definitions 有修改应该浅拷贝，下面的 else 里面 schema 没有修改，反而不需要浅拷贝

2023-09-07 01:48 UTC, 2betop commented on packages/amis-editor-core/src/component/factory.tsx
> +  let dialogIndexList = [];
这个直接记录一个最大的 index 值是不是就够了？

2023-09-07 01:55 UTC, 2betop commented on packages/amis-editor-core/src/util.ts
> +      if (value === 'drawer' && !object.drawer.$ref) {
请精简一下这行以下的代码，比如 

```
const modal = object[value === 'drawer' ? 'drawer': 'dialog'];
const titleMap = {
  drawer: '抽屉',
  confirmDialog: '确认对话框'
}
const title = `${modal?.title || '-'}（${titleMap[value] || '弹窗'}）`;
dialogActions.push({
  label: title,
  value: modal
})
```

2023-09-07 01:57 UTC, 2betop commented on packages/amis-editor-core/src/util.ts
> +  dialogActions: any[],
能用纯函数还是尽量用纯函数，这里为何不直接 return 一个数组，而要传给数组引用，在这个函数里面修改这个引用，带来副作用

2023-09-07 02:10 UTC, 2betop commented on packages/amis-editor/src/renderer/event-control/helper.tsx
> +        if (type === 'add') {
请精简以下代码

2023-09-07 02:12 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +      hideActionsOn = resolveVariableAndFilter(hideActionsOn, data);
schemaRenderer 里面会自动处理这个，不需要额外再运算，直接读取  this.props.hideActions 即可

2023-09-07 02:12 UTC, 2betop commented on packages/amis/src/renderers/Dialog.tsx
> +    let container = inDesign ? previewContainer : env?.getModalContainer;
还是没删掉？

2023-09-11 06:47 UTC, 2betop approved these changes

2023-09-11 07:33 UTC, merged