feat: 树组件优化
baidu/amis pull request #7946
Opened 2023-08-29 06:06 UTC by LTtwinkle

### 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [x] 功能增强
- [ ] 国际化语料改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 其他改动（是关于什么的改动？）

### 优化点

1. 编辑器-组件，「树选择框」改名为「树组件」；
2. 编辑器，「树组件」拖入画布的时，默认使用「浮层模式」；
3. 「树组件」新增 deferField 字段，支持 defer 字段自定义；同时编辑器配置面板，新增 deferField、deferApi 字段的配置；
4. 「树组件」内嵌模式支持 searchApi；同时编辑器配置面板，开放 searchable、searchApi 字段的配置；
5. 「树组件」扩展组件特性动作，新增、删除、编辑、刷新等；
6. 「树组件」change 事件支持获取 items；

### 更新日志

| 语言    | 更新描述 |
| ------- | -------- |
| 英文 |          |
| 中文 |   树组件优化       |

### 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-08-29 08:10 UTC, 2betop commented on packages/amis/src/renderers/Form/InputTree.tsx
> +    eachTree(options, item => {
应该用 findTree，eachTree 找到了不会中断循环

2023-08-30 02:58 UTC, lurunze1226 requested changes

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +    onEdit && onEdit(item, editItem!, true);
editItem 不需要断言吧，findTree可以直接返回目标节点

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +      resolveEventData(this.props, {value, items: options})
这里要考虑一下 items 派发的应该是过滤后的 option，而不是全量的 option

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +      deferField,
没看到声明，Schema interface上补充一下 吧

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/InputTree.tsx
> +          throw new Error(__('CRUD.invalidArray'));
这里的错误提示信息和你取值的规则不一致，不能直接用

2023-08-30 02:58 UTC, lurunze1226 commented on docs/zh-CN/components/form/input-tree.md
> +适用于需选择的数据/信息源较多时，用户可直观的知道自己所选择的数据/信息的场景。
这里补充说明一下吧，未配置 searchApi 是前端检索，配置之后就只能后端检索了

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis-editor/src/plugin/Form/TreeSelect.tsx
> +  name = '树组件';
这个 plugin 没啥用了吧

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis-editor/src/tpl/common.tsx
> +  placeholder: '懒加载对应的字段'
这个描述内容不够清晰

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis-ui/src/components/Tree.tsx
> +            !(item[deferField] && !item.loaded) ? (
不止这些，deferField 应该是 Option 层级的，其他用到的地方也要一并改了

2023-08-30 02:58 UTC, lurunze1226 commented on packages/amis-editor/src/plugin/Form/InputTree.tsx
> +            }
这里应该提示一下，key 不一定是 label 和 value，应该是 valueField 和 labelField

2023-08-31 08:21 UTC, LTtwinkle commented on packages/amis-editor/src/plugin/Form/TreeSelect.tsx
> +  name = '树组件';
有用的，会影响编辑态，中心区域，选中组件时，组件显示的标题

2023-08-31 08:22 UTC, LTtwinkle commented on packages/amis-ui/src/components/Tree.tsx
> +            !(item[deferField] && !item.loaded) ? (
都统一调整了，辛苦看下

2023-08-31 08:23 UTC, LTtwinkle commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +      deferField,
已补充

2023-11-15 05:02 UTC, lurunze1226 requested changes

2023-11-15 05:02 UTC, lurunze1226 commented on packages/amis-editor/src/plugin/Form/InputTree.tsx
> +    {
这个几个事件TreeSelect和InputTreee可以共用吧

2023-11-15 09:09 UTC, LTtwinkle commented on packages/amis/src/renderers/Form/InputTree.tsx
> +    } else if (keyword) {
后面有判断，如果 keyword 为空，直接返回全部的 options

2023-11-23 11:37 UTC, lurunze1226 requested changes

2023-11-23 11:37 UTC, lurunze1226 commented on packages/amis-ui/src/locale/zh-CN.ts
> +  'Tree.invalidArray': 'data 必须是数组',
data.options、data.items 或data必须是数组

2023-11-23 11:37 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +    const filtedOptions =
拼写错了，`filteredOptions`

2023-11-23 11:37 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/TreeSelect.tsx
> +        items: filtedOptions
同上

2023-11-27 02:43 UTC, igrowp approved these changes

2023-11-27 06:12 UTC, lurunze1226 approved these changes

2023-11-27 06:13 UTC, merged