fix:修复弹窗大纲滚动条超出无法滚动,移动端弹窗预览挂载点出错等问题
baidu/amis pull request #8166
Opened 2023-09-19 03:11 UTC by ascend13

修复:
1.大纲超出无法滚动
2.移动端弹窗预览挂载节点出错
3.编辑态弹窗添加事件报错
4.编辑态超出底部出现空白
5.移动端内容超出无法滚动
6.数据映射打平配置项清空key value
7.弹窗数据链上下文失效

2023-09-19 03:20 UTC, 2betop commented on packages/amis-editor-core/src/util.ts
> +          const store = (window as any)?.editorStore;
不允许用这个变量，可以直接 manager.store

2023-09-19 03:23 UTC, 2betop commented on packages/amis-editor-core/src/util.ts
> +                store.collectHostNodeDataSchema(triggerNodeId, data);
函数职责不单一，引入了副作用代码

2023-09-19 03:25 UTC, 2betop commented on packages/amis-ui/src/components/Modal.tsx
> +    const mobileUI = this.props.mobileUI;
不允许在这实现

2023-09-19 11:06 UTC, hsm-lv requested changes

2023-09-19 11:06 UTC, hsm-lv commented on packages/amis-editor-core/src/component/Preview.tsx
> +            ?.split('/onEvent')[0]
如果针对onEvent配置来取的话，那老的actionType方式应该就拿不到了吧

2023-09-20 02:59 UTC, 2betop approved these changes

2023-09-20 03:13 UTC, hsm-lv approved these changes

2023-09-20 03:31 UTC, merged