feat: 支持图片点击/鼠标移入移出事件 & 支持图片预览放大缩小动作
baidu/amis pull request #8266
Opened 2023-09-27 07:14 UTC by chengjinyang0

### 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化语料改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 其他改动（是关于什么的改动？）

### 需求背景和解决方案

https://ku.baidu-int.com/knowledge/HFVrC7hq1Q/tQvrZcAEPS/GxsYWwEpj5/puZv4Q7O4IVnAm

### 更新日志

| 语言    | 更新描述 |
| ------- | -------- |
| 英文 |          |
| 中文 |  支持图片点击/鼠标移入移出事件 & 支持图片预览放大缩小动作  |

### 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-09-28 07:26 UTC, hsm-lv requested changes

2023-09-28 07:26 UTC, hsm-lv commented on packages/amis/src/renderers/Image.tsx
> +    } else {
不是互斥的关系，需要先执行事件动作，再执行clickAction

2023-09-28 07:26 UTC, hsm-lv commented on packages/amis/src/renderers/Image.tsx
> +    } else {
另外，补下文档和单测

2023-10-30 04:43 UTC, hsm-lv requested changes

2023-11-03 01:57 UTC, hsm-lv requested changes

2023-11-03 01:57 UTC, hsm-lv commented on packages/amis-editor/src/plugin/Image.tsx
> +          getSchemaTpl('formulaControl', {
这个测试过了？看起来应该没有在args里吧

2023-11-10 02:41 UTC, hsm-lv approved these changes

2023-11-10 03:21 UTC, 2betop approved these changes

2023-11-10 03:22 UTC, merged