fix: 修复固定表头不生效问题
baidu/amis pull request #8332
Opened 2023-10-10 03:26 UTC by huangxj29

2023-10-10 03:30 UTC, 2betop commented
?

2023-10-10 03:45 UTC, huangxj29 commented
> ?，能说一下什么 case 下不生效吗？

官网地址 https://aisuda.bce.baidu.com/amis/examples/crud/fixed
![image](https://github.com/baidu/amis/assets/22715374/c48e2132-e408-454a-86ca-a89d77863a3b)
3.4.2版本中，示例的固定表头不生效

2023-10-10 03:49 UTC, 2betop commented
请提供一下浏览器信息，我这边看没这个问题

2023-10-10 05:38 UTC, huangxj29 commented
chrome 版本 87.0.4280.141

2023-10-11 02:13 UTC, 2betop requested changes

2023-10-11 02:13 UTC, 2betop commented on packages/amis-ui/scss/components/_table.scss
> +    .#{$ns}Table-table {
table 有  tableLayout 配置，不要强制配置成 fixed。

auto 能够自动撑开内容。fixed 虽然精准但是有时候内容显示不全

2023-10-11 02:14 UTC, 2betop commented on packages/amis-core/src/store/table.ts
> +        table.querySelectorAll(':scope>thead>tr>th[data-index]')
这是为啥来着？按理读取 colgroup 是一样的

2023-10-11 02:21 UTC, huangxj29 commented on packages/amis-core/src/store/table.ts
> +        table.querySelectorAll(':scope>thead>tr>th[data-index]')
我这边取 colgroup 的宽度是 0

2023-10-11 02:22 UTC, huangxj29 commented on packages/amis-ui/scss/components/_table.scss
> +    .#{$ns}Table-table {
如果不使用fixed，表格加上边框后，会对不齐

2023-10-11 02:26 UTC, 2betop commented on packages/amis-ui/scss/components/_table.scss
> +    .#{$ns}Table-table {
可能是前面那个 clientWidth 和 offsetWidth 的问题？是不是按你那样改了就够了？

2023-10-11 03:14 UTC, huangxj29 commented on packages/amis-ui/scss/components/_table.scss
> +    .#{$ns}Table-table {
fixed 只加在固定表头，固定表头的宽度是由下面的表格宽度决定，所以不会内容显示不全；
如果不加这个属性，在表格设置不换行的情况下，内容过宽 colgroup 的宽度设置会失效

2023-10-11 03:23 UTC, 2betop commented
thx

2023-10-11 03:23 UTC, 2betop approved these changes

2023-10-11 06:07 UTC, lurunze1226 approved these changes

2023-10-11 06:08 UTC, merged