feat: 新增常用动作
baidu/amis pull request #8430
Opened 2023-10-19 03:07 UTC by chengjinyang0

### 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化语料改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 其他改动（是关于什么的改动？）

### 需求背景和解决方案

背景：事件动作中的组件特性动作很常见但是在很底下。
方案：新增常用动作，记录用户最近使用的5个动作

### 更新日志

| 语言    | 更新描述 |
| ------- | -------- |
| 英文 |          |
| 中文 | 新增常用动作 |

### 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-11-02 12:10 UTC, igrowp requested changes

2023-11-02 12:10 UTC, igrowp commented on packages/amis-editor/src/renderer/event-control/action-config-dialog.tsx
> +                  ...this.getCommonActionSchema()
执行getCommonActionSchema函数可以存一下，上面length判断和这里重复执行了2遍

2023-12-01 03:17 UTC, igrowp approved these changes

2023-12-01 06:47 UTC, hsm-lv approved these changes

2023-12-01 08:05 UTC, merged