feat: 子编辑器公式输入框变量中加入宿主组件上下文变量的声明
baidu/amis pull request #8865
Opened 2023-11-23 04:41 UTC by igrowp

### What

对于picker、list等组件，配置项需要打开子编辑器弹窗，但子编辑器弹窗中fx没有携带当前组件的上下文变量

### Why

### How
在打开子编辑器时收集组件的上下文变量，在打开fx弹窗时对变量进行注入来获取宿主组件的上下文变量

2023-11-23 05:05 UTC, hsm-lv requested changes

2023-11-23 05:05 UTC, hsm-lv commented on packages/amis-editor-core/src/component/Editor.tsx
> +  hostContextVariables?: Array<{label: string; children?: Array<any>}>;
看下里面的getHostNodeDataSchema能否满足

2023-11-23 13:00 UTC, hsm-lv approved these changes

2023-11-24 02:06 UTC, wibetter approved these changes

2023-11-24 05:12 UTC, merged