feat:Pagination组件省略部分支持切换页码
baidu/amis pull request #9017
Opened 2023-12-05 03:01 UTC by yujinghan

本次pagination组件优化点总结;
1. 分页组件页码缩略「…」处优化（参考：https://ant-design.antgroup.com/components/pagination-cn#components-pagination-demo-mini）
-  鼠标移入「…」时，显示箭头，点击后支持向后切换多页，页数可在「组件-属性」中进行配置，配置项放置在“最多按钮数”后面，名称为“多页跳转页数”，默认值为5
- 向前/后多页跳转时，当前选中页也随之向后跳转，并将对应页码进行高亮
- 当前所选页数向前/后多页跳转后的页码小于/大于最小/最大页时，默认跳转至最小/最大页（如当前所选页为4，向前跳转5页后为页1）
2. 分页组件尺寸配置放置在「组件-外观」处，支持两种尺寸：default（默认）、small，small样式尺寸参考antd；
3. 分页的「组件-属性」配置中的模式支持默认和简约，简约样式优化，简介模式下支持input框跳转，支持键盘上下键跳转。

2023-12-07 11:39 UTC, lurunze1226 requested changes

2023-12-07 11:39 UTC, lurunze1226 commented on docs/zh-CN/components/pagination.md
> +### 基本用法
默认从二级标题开始吧

2023-12-07 11:39 UTC, lurunze1226 commented on docs/zh-CN/components/pagination.md
> +| ellipsisPageGap      | `number` \| `string`                 | 5                                    | 多页跳转页数，页数较多出现`...`时点击省略号时每次前进/后退的页数，默认为5  |
这个属性有必要吗？是不是和`maxButtons`有关，默认应该是`Num(maxButtons) - 2`

2023-12-08 09:49 UTC, yujinghan commented on docs/zh-CN/components/pagination.md
> +| ellipsisPageGap      | `number` \| `string`                 | 5                                    | 多页跳转页数，页数较多出现`...`时点击省略号时每次前进/后退的页数，默认为5  |
有，跳转页数不依赖于maxButtons，提供个配置项，方便页数较多时跳转大页数

2023-12-14 03:04 UTC, lurunze1226 requested changes

2023-12-14 03:04 UTC, lurunze1226 commented on packages/amis-ui/scss/components/_pagination.scss
> +  &-simplego {
![image](https://github.com/baidu/amis/assets/36724300/55163b70-6744-4846-bd6f-fe07ab4684a0)

这里的间距顺便调一下

2023-12-14 03:04 UTC, lurunze1226 commented on packages/amis-ui/src/components/Pagination.tsx
> +      simplePager = (
简洁模式也支持一下`size: sm`

2023-12-14 03:04 UTC, lurunze1226 commented on docs/zh-CN/components/pagination.md
> +| size      | `'sm' \| 'md'`               | `md`                                    | 组件尺寸，支持`md`、`sm`设置  |
表格最尾列加一下属性引入的版本，参考其他文档

2023-12-21 12:19 UTC, lurunze1226 approved these changes

2023-12-27 02:36 UTC, 2betop approved these changes

2023-12-28 06:51 UTC, merged