feat: Progress组件支持事件动作
baidu/amis pull request #9071
Opened 2023-12-08 03:35 UTC by Hsirius

### What

### Why

### How

2023-12-12 10:34 UTC, nwind approved these changes

2023-12-12 11:46 UTC, hsm-lv requested changes

2023-12-12 11:46 UTC, hsm-lv commented on packages/amis-editor/src/plugin/Progress.tsx
> +      description: '将值重置为resetValue，若没有配置resetValue，则清空'
progress不是一个表单项，应该不存在resetValue

2023-12-12 11:46 UTC, hsm-lv commented on packages/amis/src/renderers/Progress.tsx
> +    if (typeof value === 'number' || typeof +value === 'number') {
非数字为100是什么逻辑？

2023-12-12 11:46 UTC, hsm-lv commented on docs/zh-CN/components/progress.md
> +## 动作表
缺少单测

2023-12-12 11:46 UTC, hsm-lv commented on docs/zh-CN/components/progress.md
> +| setValue | `value: string` \| `number` 更新的值 | 更新数据                                               |
value为number

2023-12-14 03:40 UTC, Hsirius commented on packages/amis/src/renderers/Progress.tsx
> +    if (typeof value === 'number' || typeof +value === 'number') {
传success或者error的时候让进度达到100来着

2023-12-14 03:40 UTC, Hsirius commented on packages/amis-editor/src/plugin/Progress.tsx
> +      description: '将值重置为resetValue，若没有配置resetValue，则清空'
这里表达有误，已修改

2023-12-14 03:41 UTC, Hsirius commented on docs/zh-CN/components/progress.md
> +| setValue | `value: string` \| `number` 更新的值 | 更新数据                                               |
不一定，"60"这种也支持的

2023-12-14 09:09 UTC, Hsirius commented on docs/zh-CN/components/progress.md
> +## 动作表
已添加

2023-12-27 12:55 UTC, hsm-lv approved these changes

2023-12-27 12:55 UTC, merged