Fix input number
baidu/amis pull request #9204
Opened 2023-12-21 06:13 UTC by gooolh

### What
1. 有单位时，默认值没有添加上单位
2. 点击事件阻止冒泡
### Why
默认值未处理单位
阻止冒泡事件
### How

2023-12-21 06:25 UTC, lurunze1226 requested changes

2023-12-21 06:25 UTC, lurunze1226 commented on packages/amis/src/renderers/Form/InputNumber.tsx
> +      setPrinstineValue(this.getValue(value));
补充一下初始值带单位的单测用例

2023-12-21 07:00 UTC, lurunze1226 requested changes

2023-12-21 07:00 UTC, lurunze1226 commented on packages/amis/__tests__/renderers/Form/number.test.tsx
> +  expect(container).toMatchSnapshot();
后面两行不需要，前面的逻辑检查足够了，不需要快照，测试单位的那个已经覆盖了

2023-12-21 09:13 UTC, lurunze1226 approved these changes

2023-12-21 09:19 UTC, 2betop commented on packages/amis/src/renderers/Form/InputNumber.tsx
> +      setPrinstineValue(this.getValue(value));
如果 value 和 this.getValue(value) 结果一样呢？是不是不应该触发？

2023-12-21 09:22 UTC, 2betop commented
请补充这个场景用例

form 配置 initApi，初始不带单位，通过按钮点击后，重新拉取 initApi，也没有带单位，不修改直接提交，这个数值预期应该是要带单位的。

2023-12-22 06:04 UTC, hsm-lv approved these changes

2023-12-22 06:04 UTC, merged

2023-12-25 10:11 UTC, 2betop commented on packages/amis/src/renderers/Form/InputNumber.tsx
> +      this.props.setPrinstineValue(this.getValue(value));
初步感觉有两个问题
1. didMount 没有相关逻辑
2. 如果 外部 value 发生变化，而且初始化之后，不应该是  setPrinstineValue 而是 onChange出去