feat: 添加InputTag组件在编辑器内的标签最大选择数量配置
baidu/amis pull request #9242
Opened 2023-12-26 08:00 UTC by blankzust

### What
开放InputTag 标签选择器的max属性配置到编辑的配置面板中
![image](https://github.com/baidu/amis/assets/8541906/c2887cb7-32c1-4baa-a615-a39c51943f89)
![image](https://github.com/baidu/amis/assets/8541906/16b5dc71-cdcb-435e-8536-5f4a84f01a78)

### Why
是一个很常见的功能
### How
修改amis-editor/src/plugin/Form/InputTag.tsx中的配置，添加如下配置
```json
{
  type: 'input-number',
  name: 'max',
  label: tipedLabel('标签的最大选择数量', '标签的最大选择数量')
}
```

2023-12-29 02:11 UTC, lurunze1226 requested changes

2023-12-29 02:11 UTC, lurunze1226 commented on packages/amis-editor/src/tpl/options.tsx
> +
没有其他组件可以复用相关的属性，建议可以直接写在组件的plugin中。另外这里应该限制一下输入的范围，最小值1

2023-12-29 02:33 UTC, blankzust commented on packages/amis-editor/src/tpl/options.tsx
> +
好，我改一下

2023-12-29 02:51 UTC, blankzust commented on packages/amis-editor/src/tpl/options.tsx
> +
改好了

2023-12-29 09:26 UTC, lurunze1226 approved these changes

2024-01-08 12:58 UTC, 2betop approved these changes

2024-01-08 12:59 UTC, merged