feat: Avatar组件支持事件动作 Close #3220
baidu/amis pull request #9272
Opened 2023-12-29 07:10 UTC by zhaojianhui-a

### What

### Why

### How

2023-12-29 09:14 UTC, hsm-lv commented
[#](https://github.com/baidu/amis/issues/3220)

2023-12-29 09:20 UTC, hsm-lv requested changes

2023-12-29 09:20 UTC, hsm-lv commented on docs/zh-CN/components/avatar.md
> +| click      | -        | 点击时触发     |
缺少单测

2024-01-02 07:10 UTC, hsm-lv approved these changes

2024-01-03 06:25 UTC, pianruijie approved these changes

2024-01-03 06:53 UTC, lurunze1226 approved these changes

2024-01-03 06:53 UTC, merged