feat: 事件动作-打开页面优化，新增内容区打开、浏览器当前页打开、浏览器新开页打开
baidu/amis pull request #9273
Opened 2023-12-29 07:17 UTC by zhaojianhui-a

### What

### Why

### How

2024-01-03 06:40 UTC, pianruijie approved these changes

2024-01-03 07:00 UTC, hsm-lv requested changes

2024-01-03 07:00 UTC, hsm-lv commented on packages/amis-core/src/actions/LinkAction.ts
> +    let apiParams = {
补充下文档说明（包括版本支持说明）、单测

2024-01-05 02:08 UTC, hsm-lv approved these changes

2024-01-05 07:54 UTC, lurunze1226 approved these changes

2024-01-05 07:54 UTC, merged

2024-03-08 02:04 UTC, hq520it commented
文档早点跟进啊！