feat: 支持PDF预览
baidu/amis pull request #9662
Opened 2024-02-27 02:51 UTC by allenve

### What

### Why

### How

2024-02-27 07:25 UTC, 2betop requested changes
react-pdf 体积较大且不是常用组件，请改成异步加载方式，同时调整 sdk 打包策略，使其单独打包，且按需加载。

2024-02-27 07:32 UTC, 2betop commented on packages/amis/src/renderers/PdfViewer.tsx
> +      return;
如果上一次加载没结束，应该是让前一个取消，而不是跳过更新逻辑

2024-02-27 07:33 UTC, 2betop commented on packages/amis/src/renderers/PdfViewer.tsx
> +      if (prevProps.data[props.name] !== props.data[props.name]) {
name 得支持路径，用 getVariable

2024-02-27 10:59 UTC, nwind commented
感觉没必要，性能还不如直接用 iframe

2024-02-29 07:56 UTC, 2betop approved these changes

2024-02-29 09:37 UTC, hsm-lv approved these changes

2024-02-29 09:37 UTC, merged

2024-04-17 08:07 UTC, Bamzc commented
这个组件库是否可以去掉?react-pdf 体积较大且不是常用组件，并且还会影响服务器部署构建过程。react-pdf里面的依赖canvas ，他的 C/C++ 部分依赖于 cairo、pango 等图形库,编译这些库需要大量 CPU 和内存资源。如果硬件资源较差,编译时间会很长。可能会持续几个小时！