feat: Combo组件支持拖拽事件 Close: #9538
baidu/amis pull request #9668
Opened 2024-02-27 09:39 UTC by CheshireJCat

### What

### Why

### How

2024-02-27 12:19 UTC, hsm-lv requested changes

2024-02-27 12:21 UTC, hsm-lv requested changes

2024-02-27 12:21 UTC, hsm-lv commented on packages/amis/src/renderers/Form/Combo.tsx
> +              name
是要做resolveEventData吗？

2024-02-29 03:57 UTC, 2betop commented on packages/amis/src/renderers/Form/Combo.tsx
> +          if (rendererEvent?.prevented) {
+1

2024-03-14 02:45 UTC, hsm-lv approved these changes

2024-03-14 03:07 UTC, hsm-lv approved these changes

2024-03-20 03:46 UTC, 2betop approved these changes

2024-03-20 03:46 UTC, merged