Feat 1：为table的select动作增加一个参数：追加选择还是覆盖
baidu/amis pull request #9791
Opened 2024-03-13 08:39 UTC by citywalki

### What

### Why

### How

2024-03-13 10:39 UTC, 2betop commented on packages/amis/src/renderers/Table/index.tsx
> +          args?.replaceData !== undefined
这个配置项要斟酌一下，看起来跟 data 无关，应该叫 relaceSelected ?

2024-03-13 11:51 UTC, hsm-lv requested changes

2024-03-13 11:51 UTC, hsm-lv commented on packages/amis/src/renderers/Table/index.tsx
> +            ? evalExpression(args?.replaceData, {})
用evalExpressionWithConditionBuilder吧，这样做可视化的时候可以支持条件组合

2024-03-14 02:46 UTC, hsm-lv commented on packages/amis/src/renderers/Table/index.tsx
> +          args?.replaceData !== undefined
文档和单测顺便补充一下

2024-03-14 02:52 UTC, citywalki commented on packages/amis/src/renderers/Table/index.tsx
> +            ? evalExpression(args?.replaceData, {})
> 用evalExpressionWithConditionBuilder吧，这样做可视化的时候可以支持条件组合

我看evalExpressionWithConditionBuilder是异步方法，那是再Callback里面调updateSelected吗？不然await需要把这个方法改成async，范围就大了吧？

2024-04-02 03:30 UTC, citywalki commented
抱歉，我对git分支管理不太熟，好像合并代码的时候产生了很多修改，我先把这个pr关闭

2024-04-02 03:30 UTC, closed without merging